ArkEcosystem/mainsail

- package.json
Add **test:unit** script for parallel test execution on local machine.
> chore: add `test:unit` script

- packages/consensus/package.json
- packages/consensus/source/broadcaster.ts
- packages/consensus/source/consensus.ts
- packages/consensus/source/handler.ts
- packages/consensus/source/index.ts
- packages/consensus/source/precommit.ts
- packages/consensus/source/prevote.ts
- packages/consensus/source/proposal.ts
- packages/consensus/source/round-state-repository.ts
- packages/consensus/source/round-state.ts
- packages/consensus/source/types.ts
- packages/consensus/source/validator.ts
- packages/consensus/tsconfig.json
- packages/contracts/source/identifiers.ts
- packages/core/bin/config/testnet/app.json
- packages/core/package.json
- packages/processor/source/block-processor.ts
- pnpm-lock.yaml
Implements minimal three phase consensus.
> feat(consensus): implements minimal three phase consensus

- packages/consensus/package.json
- packages/consensus/source/consensus.ts
- packages/consensus/source/index.ts
- packages/consensus/source/scheduler.test.ts
- packages/consensus/source/scheduler.ts
- packages/consensus/source/types.ts
- packages/contracts/source/identifiers.ts
- pnpm-lock.yaml
Implement Scheduler class to handle propose, prevote and precommit timeouts.
> feat(consensus): implements `Scheduler`

- packages/configuration-generator/source/generators/milestones.test.ts
- packages/configuration-generator/source/generators/milestones.ts
- packages/contracts/source/contracts/crypto/networks.ts
- packages/core/bin/config/testnet/crypto.json
- packages/crypto-config/source/configuration.test.ts
> feat: introduce`walletKeyPair`, `walletSignature`, `consensusKeyPair`, `consensusSiganture` milestone entries

- packages/consensus/source/consensus.ts
- packages/consensus/source/index.ts
- packages/consensus/source/types.ts
- packages/consensus/source/validator-repository.ts
- packages/consensus/source/validator-set.ts
- packages/consensus/source/validator.ts
- packages/contracts/source/identifiers.ts
Implements simple **ValidatorSet** and **ValidatorRepository** classes with separate bindings.
> feat(consensus): implement  initial `ValidatorSet` & `ValidatorRepository` instances

- packages/state/source/wallets/wallet-index.test.ts
- packages/state/source/wallets/wallet-repository-clone.test.ts
- packages/state/source/wallets/wallet-repository-clone.ts
- packages/state/source/wallets/wallet-repository-copy-on-write.test.ts
- packages/state/source/wallets/wallet-repository.test.ts
- packages/state/source/wallets/wallet.test.ts
- packages/state/test/setup.ts
Test wallets and repositories.
> test(state): wallets and repositories

- .gitignore
Some unit tests don't seem to clean up correctly. I always have a dirty `:memory:` file after running the tests, but it's probably not worth investigating why so we can just ignore the file.
> chore: add unit test output to gitignore

- packages/configuration-generator/source/generators/genesis-block.ts
- packages/consensus/source/index.ts
- packages/consensus/source/types.ts
- packages/consensus/source/validator.ts
- packages/contracts/source/contracts/crypto/block.ts
- packages/crypto-block/source/factory.ts
- packages/forger/source/validator.ts
- packages/test-framework/source/factories/factories/block.ts
Create block without keyPair and use wallet public key as generator.
> refactor: create block without keyPair and use wallet public key as generator

- packages/contracts/source/contracts/kernel/application.ts
- packages/crypto-consensus-bls12-381/source/index.test.ts
- packages/kernel/source/application.test.ts
- packages/kernel/source/application.ts
Exposes `isBoundTagged` from the container to test that the crypto dependencies are tagged properly.
> test(crypto-consensus-bls12-381): increase test coverage

- packages/validator-set-static/source/validator-set.test.ts
- packages/validator-set-static/test/helpers/prepare-sandbox.ts
Test creation of static validator set.
> test(validator-set-static): increase test coverage

- .github/workflows/unit.yml
> ci: add unit tests

- packages/contracts/source/contracts/crypto/block.ts
- packages/crypto-block/source/deserializer.test.ts
- packages/crypto-block/source/deserializer.ts
- packages/crypto-block/source/factory.test.ts
- packages/crypto-block/source/factory.ts
- packages/p2p/source/socket-server/controllers/post-block.test.ts
- packages/p2p/source/socket-server/controllers/post-block.ts
Add a dedicated `deserializeHeader` method, as part of an ongoing effort to make the block serializer interface cleaner, 
Also fix some tests that were broken because of copy paste / messed up typings.
> refactor(crypto-block): add `deserializeHeader`

- packages/consensus/source/consensus.ts
- packages/state/source/round-state.ts
Tweaks the logs a little bit to make them easier to parse (for me). Also disables the missed blocks output, since it's not working correctly atm.
> refactor(consensus): make logs slightly more readable

- packages/utils/source/big-number.ts
> fix(utils): use private keyword on `toBigNumber` method to support cloning BigNumber

- packages/consensus/source/consensus.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/block-processor.ts
- packages/contracts/source/contracts/consensus.ts
- packages/contracts/source/contracts/state/block-state.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/fees-burn/source/mutator.ts
- packages/processor/source/block-processor.ts
- packages/processor/source/handlers/accept-block-handler.ts
- packages/state/source/block-state.ts
- packages/state/source/database-interactions.test.ts
- packages/state/source/database-interactions.ts
- packages/state/source/mutators/attribute.ts
- packages/state/source/mutators/balance.ts
- packages/state/source/wallets/wallet-repository-clone.ts
Implement commit on BlockProcessor. Refactor /state to accept WalletRespositoryClone.
> feat: implements `commit` on BlockProcessor

- packages/consensus/source/consensus.ts
- packages/consensus/source/handler.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/crypto/messages.ts
- packages/crypto-messages/source/precommit.test.ts
- packages/crypto-messages/source/precommit.ts
- packages/crypto-messages/source/prevote.test.ts
- packages/crypto-messages/source/prevote.ts
- packages/crypto-messages/source/proposal.test.ts
- packages/crypto-messages/source/proposal.ts
- packages/processor/source/block-processor.ts
- packages/processor/source/handlers/accept-block-handler.ts
- packages/processor/source/verifiers/chained-verifier.ts
- packages/processor/source/verifiers/forged-transactions-verifier.ts
- packages/processor/source/verifiers/incompatible-transactions-verifier.ts
- packages/processor/source/verifiers/nonce-verifier.ts
- packages/processor/source/verifiers/validator-verifier.ts
- packages/processor/source/verifiers/verify-block-verifier.ts
Expose getters and use them instead toData method.
> refactor(crypto-messages): expose getters on Proposal, Prevote & Precommit

- packages/consensus/source/consensus.ts
- packages/contracts/source/contracts/consensus.ts
- packages/contracts/source/contracts/crypto/messages.ts
- packages/crypto-messages/source/factory.ts
- packages/crypto-messages/source/proposal.test.ts
- packages/crypto-messages/source/proposal.ts
- packages/validator/source/validator.ts
- pnpm-lock.yaml
> feat(crypto-messages): add `validRound` to Proposal

- packages/consensus/source/broadcaster.ts
- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/consensus/source/enums.ts
- packages/consensus/source/handler.ts
- packages/consensus/source/round-state-repository.ts
- packages/consensus/source/round-state.ts
- packages/consensus/source/scheduler.test.ts
- packages/consensus/source/scheduler.ts
- packages/consensus/source/types.ts
- packages/contracts/source/contracts/consensus.ts
- packages/processor/source/block-processor.ts
Implement full consensus service.
> feat(consensus): implements full consenus service

- packages/p2p/source/peer-communicator.ts
> fix(p2p): resolve circular dependency

- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/validator-set.ts
- packages/validator-set-static/source/validator-set.ts
> refactor(validato-set-static): make getValidatorPublicKeyByIndex sync

- packages/contracts/package.json
- packages/contracts/source/contracts/p2p/endpoints.ts
- packages/contracts/source/contracts/p2p/header.ts
- packages/contracts/source/contracts/p2p/index.ts
- packages/p2p/package.json
- packages/p2p/source/header.ts
- packages/p2p/source/socket-server/controllers/get-blocks.ts
- packages/p2p/source/socket-server/controllers/get-common-blocks.ts
- packages/p2p/source/socket-server/controllers/get-messages.ts
- packages/p2p/source/socket-server/controllers/get-peers.ts
- packages/p2p/source/socket-server/controllers/get-proposal.ts
- packages/p2p/source/socket-server/controllers/get-status.ts
- packages/p2p/source/socket-server/controllers/post-block.ts
- packages/p2p/source/socket-server/controllers/post-precommit.ts
- packages/p2p/source/socket-server/controllers/post-prevote.ts
- packages/p2p/source/socket-server/controllers/post-proposal.ts
- packages/p2p/source/socket-server/controllers/post-transactions.ts
- pnpm-lock.yaml
Extract contracts for p2p controllers.
> refactor(p2p): extract Request & Response contracts

- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/consensus.ts
- packages/contracts/source/contracts/crypto/block.ts
- packages/contracts/source/contracts/crypto/messages.ts
- packages/crypto-block/source/deserializer.ts
- packages/crypto-block/source/factory.ts
- packages/crypto-block/source/serializer.test.ts
- packages/crypto-block/source/serializer.ts
- packages/crypto-messages/source/factory.test.ts
- packages/crypto-messages/source/serializer.ts
- packages/serializer/source/serializer.ts
Use bitmap to serialize validators instead of array of booleans
> refactor(serializer): use bitmap for validators

- packages/consensus/source/consensus.ts
- packages/consensus/source/round-state.ts
- packages/crypto-messages/source/verifier.ts
- packages/crypto-messages/test/helpers/prepare-sandbox.ts
- packages/crypto-messages/test/helpers/prepare-wallet.ts
- packages/crypto-transaction-validator-registration/source/handlers/validator-registration.ts
- packages/validator-set-static/source/index.ts
- packages/validator-set-static/source/validator-set.ts
- packages/validator/source/validator.test.ts
- packages/validator/test/helpers/prepare-sandbox.ts
Rename the validator wallet attribute from `consensus.publicKey` to `validator.consensusPublicKey`
> refactor(validator): rename wallet public key attribute

- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/crypto/messages.ts
- packages/contracts/source/exceptions/crypto.ts
- packages/crypto-block/source/factory.ts
- packages/crypto-consensus-bls12-381/source/index.test.ts
- packages/crypto-consensus-bls12-381/source/index.ts
- packages/crypto-consensus-bls12-381/source/schemas.ts
- packages/crypto-messages/package.json
- packages/crypto-messages/source/factory.test.ts
- packages/crypto-messages/source/factory.ts
- packages/crypto-messages/source/index.ts
- packages/crypto-messages/source/precommit.test.ts
- packages/crypto-messages/source/precommit.ts
- packages/crypto-messages/source/prevote.test.ts
- packages/crypto-messages/source/prevote.ts
- packages/crypto-messages/source/proposal.test.ts
- packages/crypto-messages/source/proposal.ts
- packages/crypto-messages/source/schemas.test.ts
- packages/crypto-messages/source/schemas.ts
- packages/crypto-messages/source/verifier.test.ts
- packages/crypto-messages/test/fixtures/proposal.ts
- packages/crypto-messages/test/helpers/prepare-sandbox.ts
- packages/validator/source/validator.ts
- packages/validator/test/helpers/prepare-sandbox.ts
- pnpm-lock.yaml
Add schemas for proposals, prevotes and precommits
> feat(crypto-messages): add schemas

- packages/consensus/source/consensus.ts
- packages/consensus/source/scheduler.ts
- packages/contracts/source/contracts/consensus.ts
There is no more need for delayed start, since p2p message download is implemented. 
Reverts #101.
> refactor(p2p): remove delayed start

- packages/consensus/source/committed-block-state.ts
- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/consensus/source/handler.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/block-processor.ts
- packages/contracts/source/contracts/consensus.ts
- packages/processor/source/block-processor.ts
- packages/processor/source/verifiers/chained-verifier.ts
- packages/processor/source/verifiers/forged-transactions-verifier.ts
- packages/processor/source/verifiers/incompatible-transactions-verifier.ts
- packages/processor/source/verifiers/nonce-verifier.ts
- packages/processor/source/verifiers/verify-block-verifier.ts
Add support for handling CommittedBlock, that are going to be downloaded from other peers. 
TODO: 
- Check names
- add onCommittedBlock to interface
> feat(consensus): add support for handling commitedBlock

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/consensus/source/handler.ts
- packages/consensus/source/scheduler.test.ts
- packages/consensus/source/scheduler.ts
- packages/contracts/source/contracts/consensus.ts
Use lock to ensure consistency.  
Move handle method inside consensus.
> feat(consensus): use locks

- packages/contracts/source/contracts/p2p/endpoints.ts
- packages/contracts/source/contracts/p2p/header.ts
- packages/contracts/source/contracts/p2p/peer-processor.ts
- packages/contracts/source/contracts/p2p/peer.ts
- packages/p2p/source/actions/validate-and-accept-peer.test.ts
- packages/p2p/source/actions/validate-and-accept-peer.ts
- packages/p2p/source/header.ts
- packages/p2p/source/network-monitor.ts
- packages/p2p/source/network-state.test.ts
- packages/p2p/source/network-state.ts
- packages/p2p/source/peer-communicator.ts
- packages/p2p/source/peer-processor.ts
- packages/p2p/source/peer.test.ts
- packages/p2p/source/peer.ts
- packages/p2p/source/service-provider.ts
- packages/p2p/source/socket-server/plugins/accept-peer.test.ts
- packages/p2p/source/socket-server/plugins/accept-peer.ts
- packages/p2p/source/validation/formats.ts
- packages/p2p/source/validation/is-valid-peer.test.ts
- packages/p2p/source/validation/is-valid-peer.ts
- update peer state on every request
- user peer ip on validation
> refactor(p2p): change update peer state on every request

- packages/p2p/source/header.ts
- packages/p2p/source/peer-communicator.ts
- packages/p2p/source/reply-schemas.ts
- packages/p2p/source/socket-server/codecs/proto/get-blocks.proto
- packages/p2p/source/socket-server/codecs/proto/get-common-blocks.proto
- packages/p2p/source/socket-server/codecs/proto/get-messages.proto
- packages/p2p/source/socket-server/codecs/proto/get-peers.proto
- packages/p2p/source/socket-server/codecs/proto/get-proposal.proto
- packages/p2p/source/socket-server/codecs/proto/get-status.proto
- packages/p2p/source/socket-server/codecs/proto/post-precommit.proto
- packages/p2p/source/socket-server/codecs/proto/post-prevote.proto
- packages/p2p/source/socket-server/codecs/proto/post-proposal.proto
- packages/p2p/source/socket-server/codecs/proto/post-transactions.proto
- packages/p2p/source/socket-server/codecs/proto/protos.d.ts
- packages/p2p/source/socket-server/codecs/proto/protos.js
- packages/p2p/source/socket-server/plugins/header-include.ts
- packages/p2p/source/socket-server/server.ts
- Include headers into response
- Add codes support
- Extend reply schemas
- Handle headers on response
> feat(p2p): include headers into response

- packages/consensus/source/bootstrapper.ts
- packages/consensus/source/committed-block-state.ts
- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/consensus/source/handler.ts
- packages/consensus/source/proposer-picker.ts
- packages/consensus/source/round-state-repository.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/consensus.ts
- packages/contracts/source/contracts/p2p/header.ts
- packages/contracts/source/contracts/validator-set.ts
- packages/crypto-messages/source/verifier.ts
- packages/p2p/source/header.ts
- packages/p2p/source/peer-communicator.ts
- packages/p2p/source/socket-server/controllers/get-messages.ts
- packages/p2p/source/socket-server/controllers/get-proposal.ts
- packages/p2p/source/socket-server/plugins/header-include.ts
- packages/validator-set-static/source/validator-set.ts
Refactor async methods to sync.
> refactor(consensus): use sync methods

- packages/contracts/source/contracts/p2p/index.ts
- packages/contracts/source/contracts/p2p/network-monitor.ts
- packages/contracts/source/contracts/p2p/peer-discoverer.ts
- packages/contracts/source/contracts/p2p/peer-repository.ts
- packages/contracts/source/identifiers.ts
- packages/p2p/source/network-monitor.ts
- packages/p2p/source/peer-discoverer.ts
- packages/p2p/source/peer-repository.test.ts
- packages/p2p/source/peer-repository.ts
- packages/p2p/source/service-provider.ts
Extract peer discovery logic. 
Move hasMinimumPeer to repository.
> refactor(p2p): extract PeerDiscoverer

- packages/p2p/package.json
- pnpm-lock.yaml
Update [protobufjs](https://www.npmjs.com/package/protobufjs), due possible security vulnerability.
> deps(p2p): update protobuf

- packages/cli/package.json
- packages/core/package.json
- packages/kernel/package.json
- pnpm-lock.yaml
Update packages with security vulnerabilities.
> deps: update packages with security vulnerabilities

- packages/contracts/source/contracts/validator-set.ts
- packages/processor/source/block-processor.ts
- packages/state/source/state-builder.ts
- packages/state/test/setup.ts
- packages/validator-set-static/source/validator-set.ts
- packages/validator-set-vote-weighted/package.json
- packages/validator-set-vote-weighted/source/index.ts
- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
- packages/validator-set-vote-weighted/test/build-validator-and-vote-balances.ts
- packages/validator-set-vote-weighted/tsconfig.json
- pnpm-lock.yaml
Introduce new `@mainsail/validator-set-vote-weighted` package.
It's not loaded by default, so you need to update the `app.json`.
> feat(consensus): vote weighted validator set

- packages/consensus/source/proposer-picker.test.ts
- packages/consensus/source/proposer-picker.ts
- packages/contracts/source/contracts/consensus.ts
- packages/processor/source/block-processor.ts
- packages/state/source/state-builder.ts
- packages/state/test/setup.ts
Shuffle validator index at the beginning of each round / after 51 blocks
> feat(consensus): shuffle validator index at beginning of each round

- lerna.json
- package.json
- pnpm-lock.yaml
Reverts ArkEcosystem/mainsail#137, because of caching issues on new version.
> revert: update `lerna` to 7.1.4

- packages/contracts/source/contracts/database.ts
- packages/database/source/database-service.ts
- packages/state/source/state-builder.ts
- packages/state/test/setup.ts
Fix state builder to read blocks in ascending order during bootstrap
> fix(state): bootstrap blocks in ascending order

- packages/consensus/source/index.ts
- packages/contracts/source/contracts/state/state-store.ts
- packages/p2p/source/socket-server/plugins/await-block.ts
- packages/p2p/source/socket-server/utils/get-headers.test.ts
- packages/p2p/source/socket-server/utils/get-headers.ts
- packages/processor/source/handlers/accept-block-handler.ts
- packages/processor/source/verifiers/forged-transactions-verifier.ts
- packages/state/source/block-state.ts
- packages/state/source/stores/state.ts
> reafactor(state): cleanup StateStore

- packages/configuration-generator/source/generators/genesis-block.ts
- packages/contracts/source/contracts/transaction-pool/processor.ts
- packages/contracts/source/exceptions/pool.ts
- packages/crypto-block/source/verifier.ts
- packages/crypto-signature-schnorr/source/signature.ts
- packages/crypto-transaction/source/factory.ts
- packages/crypto-transaction/source/verifier.ts
- packages/fees-managed/source/matcher.ts
- packages/fees-static/source/matcher.ts
- packages/fees/source/service-provider.ts
- packages/processor/source/block-processor.ts
- packages/processor/source/verifiers/nonce-verifier.ts
- packages/state/source/transaction-validator.ts
- packages/state/source/wallets/wallet-repository-copy-on-write.ts
- packages/test-framework/source/mocks/transaction-pool-processor.ts
- packages/transaction-pool/source/collator.test.ts
- packages/transaction-pool/source/collator.ts
- packages/transaction-pool/source/errors.test.ts
- packages/transaction-pool/source/mempool.ts
- packages/transaction-pool/source/processor.test.ts
- packages/transaction-pool/source/processor.ts
- packages/transaction-pool/source/sender-state.test.ts
- packages/transaction-pool/source/sender-state.ts
- packages/transaction-pool/source/service.ts
- packages/validator/source/validator.ts
> fix(transaction-pool): tx broadcast fixes

- packages/p2p/source/network-monitor.ts
- packages/p2p/source/peer-discoverer.ts
- packages/p2p/source/peer-processor.ts
- packages/p2p/source/peer-verifier.ts
Compare against correct block. Disable peer cleansing.
> fix(p2p): verifier

- packages/contracts/source/contracts/p2p/peer-communicator.ts
- packages/contracts/source/identifiers.ts
- packages/p2p/package.json
- packages/p2p/source/defaults.ts
- packages/p2p/source/peer-communicator.ts
- packages/p2p/source/service-provider.ts
- packages/p2p/source/socket-server/plugins/rate-limit.ts
- packages/p2p/source/throttle.ts
- packages/p2p/source/utils/build-rate-limiter.ts
- pnpm-lock.yaml
Extract Throttle class Improve logic so each check and consume is executed in atomic fashion.
> fix(p2p): extract `Throttle` class

- packages/p2p/source/constants.ts
- packages/p2p/source/defaults.ts
> refactor(p2p): adjust defaults

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
> feat(consensus): improve logs

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
> refactor(consensus): remove getLockedValue & getValidValue

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
> merge: develop

- packages/api/source/controllers/consensus.ts
Expose additional data from the consensus endpoint to make debugging easier.
```
curl http://127.0.0.1:4003/api/consensus/state | jq
```
See example response below.
<details><summary>Details</summary>
<p>
```json
{
"data": {
"height": 165,
"lockedRound": 0,
"lockedValue": null,
"proposals": [
{
"data": {
"block": {
"serialized": "000161996bde8901a5000000369c79fbbae71bc1f53d0f21cd8376f97fdaf50605805e88e95fe491f08e36420000000000000000000000000000000000000000000000000000000000000000e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8556f7d1ea877b1dbc981dea4561eecc383a5e20d587f1bf2843bd33f887d8bd930"
},
"height": 165,
"round": 0,
"signature": "a1ab0a65f11e0d09cb3459cf58fe3eea630885c79b5559c25e7d7baae35971c01830b206658c6ad047faf46054ad38220928eb97a446b5c5fa2d14e46fa905941b7c2db0eae30a …
```
> feat(api): expose more consensus state

- packages/kernel/source/services/queue/drivers/memory.ts
Fix error message being omitted from the logs
> fix(kernel): queue error logging

- packages/contracts/source/contracts/p2p/peer-disposer.ts
- packages/p2p/source/downloader/block-downloader.ts
- packages/p2p/source/downloader/message-downloader.ts
- packages/p2p/source/downloader/proposal-downloader.ts
- packages/p2p/source/peer-communicator.ts
- packages/p2p/source/peer-disposer.ts
> refactor(p2p): log peer block reason

- packages/crypto-block/package.json
- packages/database/package.json
- pnpm-lock.yaml
> chore: fix workspace dependency

- package.json
Removes lerna cache, cleans packages and removes node modules.
> feat: add `clean:all` script

- packages/consensus/source/consensus.ts
- packages/consensus/source/round-state.ts
- packages/crypto-messages/source/verifier.ts
- packages/kernel/source/utils/index.ts
- packages/kernel/source/utils/is-majority.test.ts
- packages/kernel/source/utils/is-majority.ts
- packages/kernel/source/utils/is-minority.test.ts
- packages/kernel/source/utils/is-minority.ts
- packages/processor/source/verifiers/commit-verifier.ts
Move isMajority/isMinority functions to `@mainsail/utils` to remove duplication
> refactor(consensus): move isMajority / isMinority to utils

- packages/crypto-messages/source/verifier.test.ts
- packages/crypto-messages/source/verifier.ts
- packages/crypto-messages/test/helpers/prepare-wallet.ts
> fix(crypto-messages): wallet type

- packages/consensus/source/consensus.ts
- packages/consensus/source/round-state.ts
- packages/consensus/source/storage.ts
- packages/contracts/source/contracts/validator-set.ts
- packages/processor/source/verifiers/commit-verifier.ts
- packages/validator-set-static/source/validator-set.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
Log validator username instead public key.
> refactor(consensus): log validator username 

- packages/consensus/source/consensus.ts
- packages/consensus/source/precommit-processor.ts
- packages/consensus/source/prevote-processor.ts
- packages/consensus/source/proposal-processor.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/consensus/consensus.ts
Use validator indexes and remove async methods on `RoundState`. Use ValidatorWallet for proposer.
> refactor(consensus): use validator indexes and remove async methods on `RoundState`

- packages/consensus/source/consensus.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/consensus/consensus.ts
Log validator and their prevote and precommit choice.
> feat(consenus): log valdiators with votes on timeouts

- packages/configuration-generator/source/generators/genesis-block.ts
> fix(configuration-generator): create commit with round 0

- packages/consensus/source/aggregator.ts
- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/consensus/source/proposal-processor.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/consensus/consensus.ts
- packages/contracts/source/contracts/crypto/block.ts
- packages/contracts/source/contracts/crypto/index.ts
- packages/contracts/source/contracts/crypto/messages.ts
- packages/contracts/source/contracts/crypto/signatures.ts
- packages/contracts/source/contracts/validator.ts
- packages/crypto-block/source/deserializer.ts
- packages/crypto-block/source/factory.ts
- packages/crypto-block/source/serializer.ts
- packages/crypto-messages/source/verifier.ts
- packages/validator/source/validator.ts
Implement Aggregator class with `aggregate` and `verify` methods.
Remove and simplify derived logic like aggregate and verify lock proofs.
> refactor(consensus): Aggregator class implements `aggregate` and `verify` methods

- packages/consensus/source/precommit-processor.ts
- packages/consensus/source/prevote-processor.ts
- packages/consensus/source/proposal-processor.ts
Use await and check against serialized buffer without signatures.
> fix(consensus): signature verification

- packages/contracts/source/contracts/p2p/peer.ts
- packages/p2p/source/downloader/block-downloader.ts
- packages/p2p/source/downloader/message-downloader.ts
- packages/p2p/source/downloader/proposal-downloader.ts
- packages/p2p/source/header-service.ts
- packages/p2p/source/network-monitor.ts
- packages/p2p/source/network-state.ts
- packages/p2p/source/peer.ts
- packages/p2p/source/socket-server/controllers/post-precommit.test.ts
- packages/p2p/source/socket-server/controllers/post-precommit.ts
- packages/p2p/source/socket-server/controllers/post-prevote.test.ts
- packages/p2p/source/socket-server/controllers/post-prevote.ts
- packages/p2p/source/socket-server/controllers/post-proposal.test.ts
- packages/p2p/source/socket-server/controllers/post-proposal.ts
- packages/p2p/source/socket-server/plugins/accept-peer.ts
- packages/p2p/source/socket-server/server.test.ts
- packages/p2p/source/utils/index.ts
- Ban peer if received data height round
- Ban if didn't get all requested messages
- Ban if processor result is invalid
> feat(p2p): validate received data and check processor result

- packages/api-development/source/controllers/consensus.ts
Include null votes. Sort prevotes, precommits and proposals by round descending.
> refactor(api-development): `/consensus/state` sort messages by round and include null votes

- packages/validator/source/validator.ts
Use correct height to get the milestone for proposed block.
> fix(validator):  use correct milestone for block reward 

- packages/bootstrap/source/bootstrapper.ts
- packages/contracts/source/contracts/state/state-store.ts
- packages/processor/source/block-processor.ts
- packages/processor/source/verifiers/forged-transactions-verifier.ts
- packages/state/source/stores/state.ts
Skip some unnecessary actions during the bootstrap.
> feat(processor): skip block storing and ForgedTransactionsVerifier during bootstrap 

- packages/crypto-block/source/verifier.ts
- packages/processor/source/block-verifier.ts
- packages/processor/source/verifiers/index.ts
- packages/processor/source/verifiers/timestamp-verifier.ts
> feat(processor): implements timestamp verifier

- packages/consensus/source/consensus.ts
Handle scenario when process exit during the commit stage. Block is committed, but state is not updated yet.
> feat(consenus): handle stored state and height mismatch

- packages/consensus/source/proposer-picker.test.ts
- packages/consensus/source/proposer-picker.ts
- packages/kernel/source/utils/round-calculator.test.ts
- packages/kernel/source/utils/round-calculator.ts
- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
Change the proposal picker and validator sets to use the round calculator. 
The `isNewRound` function had to be slightly adjusted since we now start at height 0.
> refactor: use round calculator for checking new round

- packages/api-database/source/contracts.ts
- packages/api-database/source/identifiers.ts
- packages/api-database/source/models/block.ts
- packages/api-database/source/models/index.ts
- packages/api-database/source/models/validator-round.ts
- packages/api-database/source/repositories/validator-round-repository.ts
- packages/api-database/source/service-provider.ts
- packages/api-http/source/controllers/validator-rounds.ts
- packages/api-http/source/handlers.ts
- packages/api-http/source/resources/index.ts
- packages/api-http/source/resources/validator-round.ts
- packages/api-http/source/routes/validator-rounds.ts
- packages/api-sync/source/sync.ts
- packages/crypto-config/source/configuration.ts
- packages/kernel/source/utils/calculate-forging-info.test.ts
- packages/kernel/source/utils/calculate-forging-info.ts
- packages/kernel/source/utils/round-calculator.test.ts
- packages/kernel/source/utils/round-calculator.ts
Add `validator_rounds` table and a minimal API controller.
> feat(api): add `validator_rounds` table

- packages/api-database/source/contracts.ts
- packages/api-database/source/identifiers.ts
- packages/api-database/source/models/index.ts
- packages/api-database/source/models/wallet.ts
- packages/api-database/source/repositories/index.ts
- packages/api-database/source/repositories/wallet-repository.ts
- packages/api-database/source/service-provider.ts
- packages/api-http/source/controllers/wallets.ts
- packages/api-http/source/handlers.ts
- packages/api-http/source/resources/index.ts
- packages/api-http/source/resources/wallet.ts
- packages/api-http/source/routes/wallets.ts
- packages/api-sync/source/sync.ts
- packages/bootstrap/source/bootstrapper.ts
- packages/consensus/source/proposer-picker.test.ts
- packages/consensus/source/proposer-picker.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/crypto/block.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/processor/source/block-processor.ts
- packages/state/source/wallets/wallet-repository-clone.ts
- packages/validator-set-static/source/validator-set.ts
- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
Add `wallets` table and a minimal API controller.
> feat(api): add `wallets` table

- packages/contracts/source/contracts/p2p/endpoints.ts
- packages/contracts/source/contracts/p2p/nes.ts
- packages/contracts/source/contracts/p2p/peer-communicator.ts
- packages/contracts/source/contracts/p2p/peer-disposer.ts
- packages/p2p/source/downloader/block-downloader.ts
- packages/p2p/source/downloader/message-downloader.ts
- packages/p2p/source/downloader/proposal-downloader.ts
- packages/p2p/source/hapi-nes/client.ts
- packages/p2p/source/hapi-nes/constants.ts
- packages/p2p/source/hapi-nes/index.ts
- packages/p2p/source/peer-communicator.ts
- packages/p2p/source/peer-connector.ts
- packages/p2p/source/peer-discoverer.ts
- packages/p2p/source/peer-disposer.ts
- packages/p2p/source/peer-processor.ts
- packages/p2p/source/peer-verifier.ts
Safely dispose peer instead of block it when server is unreachable.
> feat(p2p): dispose peer when it is unreachable

- packages/api-sync/source/sync.ts
- packages/consensus/source/committed-block-state.ts
- packages/consensus/source/proposer-picker.test.ts
- packages/consensus/source/proposer-picker.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/block-processor.ts
- packages/processor/source/block-processor.ts
- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
Rename `getProposedCommitBlock` to `getCommittedBlock`.
> refactor(consensus): rename `getProposedCommitBlock` to `getCommittedBlock`

- packages/contracts/source/contracts/p2p/peer-disposer.ts
- packages/p2p/source/downloader/block-downloader.ts
- packages/p2p/source/downloader/message-downloader.ts
- packages/p2p/source/downloader/proposal-downloader.ts
- packages/p2p/source/hapi-nes/listener.ts
- packages/p2p/source/peer-communicator.ts
- packages/p2p/source/peer-connector.ts
- packages/p2p/source/peer-discoverer.ts
- packages/p2p/source/peer-disposer.ts
- packages/p2p/source/peer-processor.ts
- packages/p2p/source/peer-verifier.ts
- packages/p2p/source/service.ts
- packages/p2p/source/socket-server/controllers/post-precommit.ts
- packages/p2p/source/socket-server/controllers/post-prevote.ts
- packages/p2p/source/socket-server/controllers/post-proposal.ts
- packages/p2p/source/socket-server/plugins/base-plugin.ts
- packages/p2p/source/socket-server/plugins/codec.ts
- packages/p2p/source/socket-server/plugins/validate.test.ts
- packages/p2p/source/socket-server/plugins/validate.ts
Dispose or ban peer on error in plugins.
> feat(p2p): dispose peer and close connection on error in plugins

- packages/kernel/source/application.test.ts
- packages/kernel/source/application.ts
- packages/logger-pino/source/driver.ts
- packages/webhooks/source/service-provider.test.ts
- packages/webhooks/test/helpers/server.ts
To make sure the process is actually terminated when calling terminate.
> fix(kernel): call `process.exit` on `app.terminate`

- packages/api-database/source/contracts.ts
- packages/api-database/source/identifiers.ts
- packages/api-database/source/models/index.ts
- packages/api-database/source/models/peer.ts
- packages/api-database/source/repositories/index.ts
- packages/api-database/source/repositories/peer-repository.ts
- packages/api-database/source/service-provider.ts
- packages/api-sync/source/contracts.ts
- packages/api-sync/source/listeners/peers.ts
- packages/api-sync/source/service-provider.ts
Add a `peers` table and a corresponding listener for peer changes to periodically sync with the database. 
API controller is missing (will be added in a follow up PR).
> feat(api-sync): peers table

- packages/api-database/source/contracts.ts
- packages/api-database/source/identifiers.ts
- packages/api-database/source/models/index.ts
- packages/api-database/source/models/state.ts
- packages/api-database/source/repositories/index.ts
- packages/api-database/source/repositories/state-repository.ts
- packages/api-database/source/service-provider.ts
- packages/api-sync/source/sync.ts
Add a `state` table which contains a single row with state specific properties. 
For now we only write the `height` on commit, it will be extended as needed.
> feat(api-sync): `state` table

- packages/api-database/source/models/block.ts
- packages/api-database/source/models/transaction.ts
- packages/api-http/source/resources/transaction.ts
- packages/api-sync/source/sync.ts
Add `signature` column to `transactions` table and use consistent naming for the block signature column.
The transaction controller broke with the process separation due to no longer having the in-memory wallet repository, so I included a temporary fix to make testing easier.
> fix(api): add missing tx signature column

- packages/api-development/source/controllers/wallets.ts
- packages/state/source/wallets/wallet-repository-clone.ts
- packages/state/source/wallets/wallet-repository-copy-on-write.ts
- packages/state/source/wallets/wallet.ts
> fix(state): wallets and repositories

- packages/state/source/service-provider.ts
- packages/state/source/wallets/factory.ts
- packages/state/source/wallets/index.ts
- packages/state/source/wallets/wallet-event.ts
- packages/state/source/wallets/wallet.test.ts
- packages/state/source/wallets/wallet.ts
> refactor(state): remove wallet events

- packages/consensus/source/committed-block-state.ts
- packages/consensus/source/round-state.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/contracts/source/identifiers.ts
- packages/state/source/service-provider.ts
- packages/state/source/transaction-validator.ts
- packages/state/source/wallets/wallet-repository-clone.ts
- packages/state/test/setup.ts
Use factory to create WalletRepositoryClone.
> refactor(state): use factory for WalletRepositoryClone

- packages/contracts/source/contracts/state/attributes.ts
- packages/state/source/attributes/attribute-repository.ts
- packages/state/source/wallets/wallet.ts
Return all wallet attributes instead only dirty ones.
> fix(state): return all wallet attributes from wallet clone

- packages/api-http/integration/routes/votes.test.ts
- packages/api-http/source/controllers/votes.ts
- packages/api-http/source/handlers.ts
- packages/api-http/source/routes/votes.ts
- packages/api-http/source/schemas/transactions.ts
- packages/api-http/test/fixtures/votes.json
> feat(api): implement votes controller

- packages/api-database/source/models/state.ts
- packages/api-http/integration/routes/blockchain.test.ts
- packages/api-http/source/controllers/blockchain.ts
- packages/api-http/source/controllers/controller.ts
- packages/api-http/source/controllers/node.ts
- packages/api-sync/source/sync.ts
Sync the supply to the `state` table on each commit so the API can return the supply without having to calculate it.
> feat(api): sync supply to state table

- packages/api-http/source/plugins/comma-separated-query.ts
- packages/api-http/source/plugins/dot-separated-query.ts
- packages/api-http/source/plugins/index.ts
- packages/api-http/source/schemas/schemas.test.ts
Add missing plugins to fix range queries.
> fix(api): add missing plugins

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
Terminate process when commit fails. Handling commit error is responsibility of the processor and triggered onCommit listeners. When error is thrown process is exist to ensure valid state.
> feat(consensus): terminate app if commit fails

- packages/crypto-messages/test/helpers/prepare-sandbox.ts
- packages/crypto-transaction-validator-registration/source/handlers/validator-registration.ts
- packages/crypto-transaction-validator-resignation/source/handlers/validator-resignation.ts
- packages/state/source/attributes/attribute-repository.ts
- packages/state/source/mutators/attribute.ts
- packages/state/source/service-provider.ts
- packages/state/test/setup.ts
- packages/test-framework/source/internal/wallet-attributes.test.ts
- packages/test-framework/source/internal/wallet-attributes.ts
- packages/transactions/source/handlers/transaction.ts
- packages/validator-set-static/source/index.ts
- packages/validator-set-vote-weighted/source/index.ts
- packages/validator/test/helpers/prepare-sandbox.ts
Register validator attributes in state package. Prevent registering same attribute multiple times. Replace validatorLastBlock with validatorLastBlockId as attribute.
> refactor: register validator attributes in state package

- packages/api-database/source/models/state.ts
- packages/api-http/source/controllers/controller.ts
- packages/api-http/source/controllers/node.ts
- packages/api-sync/source/sync.ts
- packages/contracts/source/contracts/api-sync.ts
- packages/processor/source/block-processor.ts
Use a queue to defer API syncs and retry queued jobs on transient errors to make them more resilient.
> refactor(api-sync): deferred syncs, retry on exception

- packages/api-database/source/contracts.ts
- packages/api-database/source/repositories/wallet-repository.ts
- packages/api-database/source/search/criteria.ts
- packages/api-database/source/search/expressions.ts
- packages/api-database/source/search/filters/delegate-filter.ts
- packages/api-database/source/search/filters/index.ts
- packages/api-database/source/search/filters/wallet-filter.ts
- packages/api-database/source/search/query-helper.ts
- packages/api-database/source/search/search.ts
- packages/api-http/source/controllers/delegates.ts
- packages/api-http/source/controllers/validator-rounds.ts
- packages/api-http/source/handlers.ts
- packages/api-http/source/resources/delegate.ts
- packages/api-http/source/resources/index.ts
- packages/api-http/source/resources/round.ts
- packages/api-http/source/routes/delegates.ts
- packages/api-http/source/routes/validator-rounds.ts
- packages/api-http/source/schemas/delegates.ts
- packages/api-http/source/schemas/index.ts
- packages/validator-set-static/source/validator-set.test.ts
- packages/validator-set-static/source/validator-set.ts
Implement the controller for `/delegates` .
This also extends the query expression builder to support comparisons on json fields, since most queries interact with the `jsonb` attributes column.
Note that some query criteria aren't support yet due to missing wallet attributes. This will be resolved in a follow up PR.
> feat(api): implement delegates controller

- packages/proposer/source/index.ts
- packages/proposer/source/proposer-selector.test.ts
- packages/proposer/source/proposer-selector.ts
Register `validatorMatrix` attribute.
> refactor(proposer): ProposerSelector uses state attribute

- packages/api-database/source/models/wallet.ts
- packages/api-database/source/search/criteria.ts
- packages/api-database/source/search/expressions.ts
- packages/api-database/source/search/filters/delegate-filter.ts
- packages/api-database/source/search/query-helper.ts
- packages/api-http/source/schemas/delegates.ts
- packages/state/source/mutators/attribute.ts
- packages/state/source/service-provider.ts
- packages/state/source/wallets/wallet.ts
- packages/state/test/setup.ts
Write `forgedFees`, `forgedRewards` and `forgedTotal` in the attribute mutator on each processed block.
Also update the API to support the new fields.
> feat(state): write `forgedFees`, `forgedRewards` and `forgedTotal` attributes for validators

- packages/api-database/package.json
- packages/api-database/source/migrations.ts
- packages/api-database/source/migrations/1697617471901-CreateIndexes.ts
- packages/api-http/test/fixtures/votes.json
Add a migration to create common indexes needed by the API.
> feat(api-database): add indexes

- packages/contracts/source/contracts/state/wallets.ts
- packages/kernel/source/utils/calculate-forging-info.test.ts
- packages/kernel/source/utils/calculate-forging-info.ts
- packages/kernel/source/utils/index.ts
- packages/kernel/source/utils/supply-calculator.test.ts
- packages/kernel/source/utils/supply-calculator.ts
- packages/state/source/service-provider.ts
- packages/state/source/wallets/validator-wallet.ts
- packages/state/test/setup.ts
- packages/test-framework/source/internal/wallet-attributes.ts
- packages/validator-set-static/source/validator-set.ts
- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
> feat(validator): add `validatorApproval` attribute

- .github/workflows/integration.yml
- docker-compose.yml
> chore: use postgres 16

- packages/contracts/source/exceptions/consensus.ts
- packages/contracts/source/exceptions/index.ts
- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
Throw an exception in the rare case when there are less registered validators than required by the current milestone.
> fix(validator-set): throw exception when not enough registered validators

- packages/kernel/source/services/queue/drivers/memory.test.ts
The elapsed time assertion has been randomly failing on my machine since forever. I think we can just remove the problematic lines since they don't add much value in the first place.
> fix(test): remove flaky time check

- packages/bootstrap/source/bootstrapper.ts
- packages/processor/source/block-processor.ts
Skip logs on bootstrap. Interrupt processing every few block to fix issues when logger might get stuck.
> fix(block-processor): skip logs on bootstrap

- packages/api-database/source/contracts.ts
- packages/api-database/source/repositories/peer-repository.ts
- packages/api-database/source/search/criteria.ts
- packages/api-database/source/search/filters/index.ts
- packages/api-database/source/search/filters/peer-filter.ts
- packages/api-http/integration/routes/peers.test.ts
- packages/api-http/source/controllers/peers.ts
- packages/api-http/source/handlers.ts
- packages/api-http/source/resources/index.ts
- packages/api-http/source/resources/peer.ts
- packages/api-http/source/routes/peers.ts
- packages/api-http/test/fixtures/peers.json
> feat(api): add peers route & controller

- packages/api/package.json
Add script to run api on local testnet.
> feat(api): add `api:testnet` script

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/state/source/wallets/validator-wallet.ts
Use validators username in logs if username exists.
> feat(consensus): use validator username in logs

- packages/api-development/source/controllers/blocks.ts
- packages/bootstrap/source/bootstrapper.ts
- packages/contracts/source/contracts/database.ts
- packages/contracts/source/identifiers.ts
- packages/database/source/database-service.test.ts
- packages/database/source/database-service.ts
- packages/database/source/index.ts
- packages/p2p/source/peer-verifier.ts
- packages/p2p/source/socket-server/controllers/get-blocks.test.ts
- packages/p2p/source/socket-server/controllers/get-blocks.ts
- packages/processor/source/block-processor.ts
Blocks are stored and accessible only be heights.  Redundant or similar methods are removed.
> refactor(database): remove blocksByHeight store and refactor database

- packages/contracts/source/contracts/state/service.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/contracts/source/contracts/transaction-pool/sender-mempool.ts
- packages/contracts/source/contracts/transaction-pool/sender-state.ts
- packages/state/source/service-provider.ts
- packages/state/source/service.ts
- packages/state/source/wallets/index.ts
- packages/state/source/wallets/wallet-repository-by-sender.test.ts
- packages/state/source/wallets/wallet-repository-by-sender.ts
- packages/state/source/wallets/wallet-repository.ts
- packages/transaction-pool/source/mempool.ts
- packages/transaction-pool/source/sender-mempool.ts
- packages/transaction-pool/source/sender-state.test.ts
- packages/transaction-pool/source/sender-state.ts
- packages/transaction-pool/source/service-provider.ts
Implement WalletRepositoryBySender from previous WalletRepositoryCopyOnWrite. WalletRepostiroy is used for sender in mempool.
> refactor(state): implements WalletRepository for mempool sender

- packages/transaction-pool/source/defaults.ts
- packages/transaction-pool/source/service-provider.test.ts
Use correct data paths to store sqlite DB.
> fix(transaction-pool): use correct data path

- packages/crypto-address-bech32m/source/address.factory.ts
Use public key factory to calculate addresses.
> fix(bech32m): implement address factory stubs

- packages/api-development/source/controllers/api-nodes.ts
- packages/api-development/source/handlers.ts
- packages/api-development/source/routes/api-nodes.ts
New endpoint to get API nodes.
> feat(api-development): add GET `/api-nodes` endpoint

- packages/api-database/source/contracts.ts
- packages/api-database/source/identifiers.ts
- packages/api-database/source/models/api-node.ts
- packages/api-database/source/models/index.ts
- packages/api-database/source/repositories/api-node-repository.ts
- packages/api-database/source/repositories/index.ts
- packages/api-database/source/search/criteria.ts
- packages/api-database/source/search/filters/api-node-filter.ts
- packages/api-database/source/search/filters/index.ts
- packages/api-database/source/service-provider.ts
- packages/api-http/integration/routes/api-nodes.test.ts
- packages/api-http/source/controllers/api-nodes.ts
- packages/api-http/source/handlers.ts
- packages/api-http/source/resources/api-node.ts
- packages/api-http/source/resources/index.ts
- packages/api-http/source/routes/api-nodes.ts
- packages/api-http/test/fixtures/api-nodes.json
- packages/api-http/test/helpers/prepare-sandbox.ts
- packages/api-sync/source/listeners.ts
- packages/api-sync/source/listeners/api-nodes.ts
- packages/contracts/source/contracts/p2p/peer.ts
- packages/kernel/source/enums/events.ts
- packages/p2p/source/peer-api-node-processor.ts
Extend api-sync and api-http to support API nodes.
> feat(api-http): add `/api-nodes` endpoint

- packages/consensus/package.json
- packages/database/package.json
- packages/storage-lmdb/package.json
- pnpm-lock.yaml
Upgrade [lmdb](https://www.npmjs.com/package/lmdb) version.
> deps: upgrade `lmdb` version to `2.9.1`

- packages/validator/source/validator.ts
- packages/validator/test/helpers/prepare-sandbox.ts
Use state to get last block instead accessing database.
> perf(validator): use state to access last block

- packages/api-development/source/controllers/consensus.ts
Get values form consensus service and roundStateRepository.
> fix(api-development): don't access database to get state

- packages/api-http/integration/routes/blockchain.test.ts
- packages/api-http/source/controllers/blockchain.ts
> fix(api-http): return height as number

- packages/crypto-transaction-multi-payment/source/versions/1.ts
Allow vendor fields on multi payments.
> fix(crypto-transaction-multi-payment): allow vendor field

- packages/consensus/source/processors/precommit-processor.ts
- packages/consensus/source/processors/prevote-processor.ts
- packages/consensus/source/processors/proposal-processor.ts
- packages/crypto-messages/source/factory.test.ts
- packages/crypto-messages/source/factory.ts
- packages/validator/test/helpers/prepare-sandbox.ts
Use worker pool for consensus message signing and verification.
> perf(consensus): use worker for message sign & verify

- .prettierignore
- lerna.json
- nx.json
- package.json
- pnpm-lock.yaml
> deps: update lerna

- packages/contracts/source/contracts/p2p/peer-api-node-discoverer.ts
- packages/p2p/source/actions/index.ts
- packages/p2p/source/actions/revalidate-api-node.ts
- packages/p2p/source/peer-api-node-discoverer.ts
- packages/p2p/source/peer-api-node-processor.ts
- packages/p2p/source/service-provider.ts
- packages/p2p/source/service.ts
Discover new API nodes from existing peers and validate API nodes after they have been accepted (randomly after 10-20 minutes).
> feat(p2p): periodically refresh api nodes

- .prettierignore
- lerna.json
- nx.json
- package.json
- pnpm-lock.yaml
Reverts ArkEcosystem/mainsail#365. 
NX incorrect cache handling on linux.
> revert: "deps: update lerna"

- packages/consensus/source/consensus.ts
- packages/database/source/index.ts
Await block processing on dispose and persist cached blocks.
> fix: await block processing and persist blocks on dispose

- packages/consensus/source/index.ts
- packages/consensus/source/round-state.ts
Clear storage before storing state on dispose.
> fix(consenus): clear storage before storing state

- packages/configuration-generator/source/generators/genesis-block.test.ts
- packages/configuration-generator/source/generators/genesis-block.ts
- packages/crypto-transaction/source/builders.ts
> fix(configuration-generator): ensure genesis block is always valid

- packages/processor/source/block-verifier.ts
- packages/processor/source/verifiers/generator-verifier.ts
- packages/processor/source/verifiers/index.ts
> feat(block-verifier): implements generator verifier

- packages/contracts/source/contracts/state/index.ts
- packages/contracts/source/contracts/state/repository.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/state/source/repository.ts
- packages/state/source/store.ts
- packages/state/source/wallets/wallet.ts
Extract common repository logic from wallet and state.
> refactor(state): extract `Repository`

- packages/contracts/source/exceptions/crypto.ts
> refactor(validator-registration): change misleading message in WalletIsAlreadyValidatorError

- packages/contracts/source/contracts/state/attributes.ts
- packages/proposer/source/index.ts
- packages/proposer/source/selector.test.ts
- packages/state/source/attributes/attribute-repository.ts
- packages/state/source/attributes/big-number-attribute.ts
- packages/state/source/attributes/factory.ts
- packages/state/source/attributes/generic-attribute.ts
- packages/state/source/attributes/object-attribute.ts
- packages/state/source/repository.ts
- packages/state/source/store.test.ts
- packages/state/source/store.ts
- packages/state/source/wallets/factory.ts
- packages/state/source/wallets/wallet-repository-clone.test.ts
- packages/state/source/wallets/wallet.test.ts
- packages/state/source/wallets/wallet.ts
- packages/state/test/setup.ts
- packages/test-framework/source/internal/wallet-attributes.ts
- packages/transactions/source/handlers/handler-provider.ts
- packages/transactions/source/handlers/handler-registry.test.ts
Rename `IAttribute` to `Attribute`
> refactor(contracts): remove attribute prefix

- packages/api-http/test/fixtures/node_configuration.json
- packages/configuration-generator/source/configuration-generator.test.ts
- packages/configuration-generator/source/generators/milestones.test.ts
- packages/configuration-generator/source/generators/milestones.ts
- packages/core/bin/config/testnet/mainsail/crypto.json
- packages/core/source/commands/config-generate.test.ts
- packages/crypto-config/source/configuration.test.ts
- packages/crypto-config/source/configuration.ts
- packages/crypto-messages/source/keywords.test.ts
- packages/crypto-messages/source/keywords.ts
- packages/kernel/source/services/schedule/block-job.ts
- packages/kernel/source/utils/round-calculator.test.ts
- packages/kernel/source/utils/round-calculator.ts
- packages/kernel/source/utils/supply-calculator.test.ts
- packages/proposer/source/selector.test.ts
- packages/proposer/source/selector.ts
- packages/validator-set-static/source/validator-set.test.ts
- packages/validator-set-static/source/validator-set.ts
- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
Allow the number of `activeValidators` to be set on height 1 instead of height 0.
Required for #395
> refactor(crypto): allow 0 active validators on genesis

- packages/contracts/source/contracts/state/store.ts
- packages/processor/source/block-processor.ts
- packages/proposer/source/selector.test.ts
- packages/proposer/source/selector.ts
- packages/state/source/service.ts
- packages/state/source/store.test.ts
- packages/state/source/store.ts
- packages/validator-set-static/source/validator-set.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
Set configuration height before calling onCommit handler.
> refactor(processor): set configuration height before calling onCommit handler

- packages/state/source/wallets/wallet-repository-clone.ts
Supports `allByIndex` on `WalletRepositoryClone`.
> fix(state): supports `allByIndex` on `WalletRepositoryClone`

- packages/bootstrap/source/bootstrapper.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/contracts/source/contracts/validator-set.ts
- packages/state/source/service-provider.ts
- packages/state/source/wallets/validator-wallet.ts
- packages/validator-set-static/source/validator-set.ts
- packages/validator-set-vote-weighted/source/index.ts
- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
> feat(validator-set): support state exports

- packages/consensus/source/commit-state.ts
- packages/core/bin/config/testnet/mainsail/app.json
- packages/core/package.json
- packages/validator-set-static/source/validator-set.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
- pnpm-lock.yaml
> feat(validator-set): switch from static to vote weighted

- .eslintrc.js
- packages/api-database/source/contracts.ts
- packages/api-database/source/search/filters/api-node-filter.ts
- packages/api-database/source/search/filters/block-filter.ts
- packages/api-database/source/search/filters/delegate-filter.ts
- packages/api-database/source/search/filters/peer-filter.ts
- packages/cli/source/components/box.ts
- packages/cli/source/components/error.ts
- packages/cli/source/components/fatal.ts
- packages/cli/source/components/info.ts
- packages/cli/source/components/listing.ts
- packages/cli/source/components/log.ts
- packages/cli/source/components/new-line.ts
- packages/cli/source/components/success.ts
- packages/cli/source/components/table.ts
- packages/cli/source/components/title.ts
- packages/cli/source/components/warning.ts
- packages/cli/source/utils/process.ts
- packages/contracts/source/contracts/crypto/commit.ts
- packages/contracts/source/contracts/crypto/identities.ts
- packages/contracts/source/contracts/crypto/transactions.ts
- packages/contracts/source/contracts/kernel/repository.ts
- packages/contracts/source/contracts/kernel/validation.ts
- packages/contracts/source/contracts/p2p/header.ts
- packages/contracts/source/contracts/types/index.ts
- packages/utils/source/map-array.ts
- packages/utils/source/reduce-array.ts
Promote [import/no-cycle](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md) from warning to error and resolve all cyclic imports.
> fix: resolve all eslint cyclic import errors

- packages/api/source/commands/config-cli.ts
- packages/core/source/commands/config-cli.ts
Add support for `alpha` channel.
> fix(cli): support alpha channel

- packages/cli/source/contracts.ts
- packages/cli/source/services/updater.ts
- packages/core/source/commands/update.ts
Add force flag to the update check function and additionally compare against the last seen version in subsequent runs instead of blanket returning false.
> feat(cli): add force flag on Updater.check  

- packages/api/source/commands/config-cli.ts
- packages/cli/source/contracts.ts
- packages/cli/source/services/config.ts
- packages/cli/source/services/updater.test.ts
- packages/cli/source/services/updater.ts
- packages/contracts/source/constants/channels.ts
- packages/contracts/source/constants/index.ts
- packages/core/source/cli.ts
- packages/core/source/commands/config-cli.ts
Log available updates. Extract channels.
> feat(cli): log when update is avaliable

- packages/cli/source/services/installer.test.ts
- packages/cli/source/services/installer.ts
- packages/cli/source/services/source-providers/abstract-source.ts
- packages/cli/source/services/source-providers/file.test.ts
- packages/cli/source/services/source-providers/git.test.ts
- packages/cli/source/services/source-providers/npm.test.ts
`pnpm` is default package manager.
> feat(cli): `pnpm` is default package manager

- packages/core/source/commands/config-publish-custom.ts
Implements `config:publish:custom` for setting **app.json** and **crypto.json** from online sources.
> feat(core): implements `config:publish:custom`

- packages/core/source/commands/config-publish-custom.ts
- set peer.json rom online soruce, or set default
- simpler .env file
- initial validators.json
> feat(core): set `peers.json` from online surce in `config:publish:custom` command

- packages/api/source/commands/api-log.ts
- packages/api/source/commands/api-restart.test.ts
- packages/api/source/commands/api-restart.ts
- packages/api/source/commands/api-start.test.ts
- packages/api/source/commands/api-start.ts
- packages/api/source/commands/api-status.test.ts
- packages/api/source/commands/api-status.ts
- packages/api/source/commands/api-stop.test.ts
- packages/api/source/commands/api-stop.ts
- packages/cli/source/application-factory.ts
- packages/cli/source/contracts.ts
- packages/cli/source/utils/process.test.ts
- packages/cli/source/utils/process.ts
- packages/core/source/commands/core-log.ts
- packages/core/source/commands/core-restart.test.ts
- packages/core/source/commands/core-restart.ts
- packages/core/source/commands/core-start.test.ts
- packages/core/source/commands/core-start.ts
- packages/core/source/commands/core-status.test.ts
- packages/core/source/commands/core-status.ts
- packages/core/source/commands/core-stop.test.ts
- packages/core/source/commands/core-stop.ts
> refactor: use `mainsail` for process names

- docker/production/devnet/docker-compose-build.yml
- docker/production/devnet/docker-compose.yml
- docker/production/mainnet/docker-compose-build.yml
- docker/production/mainnet/docker-compose.yml
- docker/testnet/README.md
- docker/testnet/api/docker-compose.yml
- docker/testnet/core/docker-compose.yml
- Update Docker Hub paths and container names. 
- Compose files version update.
- Update README.
> chore: dockerhub image names change

- .github/workflows/publish-develop.yml
- scripts/dist-tag-latest.sh
- scripts/publish/alpha.sh
- scripts/publish/beta.sh
- scripts/publish/latest.sh
- scripts/publish/next.sh
- scripts/publish/rc.sh
Set latest tag on release. 
Remove unused publish scripts.
> chore: set `latest` NPM tag on release

- packages/bootstrap/source/bootstrapper.ts
Check config and stored genesis block matches.
> feat(bootstrap): compare stored genesis block with config

- packages/configuration-generator/package.json
- packages/configuration-generator/source/application-factory.ts
- packages/contracts/source/contracts/crypto/transactions.ts
- packages/contracts/source/exceptions/crypto.ts
- packages/crypto-address-keccak256/source/index.ts
- packages/crypto-key-pair-ecdsa/source/index.ts
- packages/crypto-transaction-evm-call/package.json
- packages/crypto-transaction-evm-call/source/builder.ts
- packages/crypto-transaction-evm-call/source/handlers/evm-call.ts
- packages/crypto-transaction-evm-call/source/versions/1.test.ts
- packages/crypto-transaction-evm-call/source/versions/1.ts
- packages/crypto-transaction-transfer/source/versions/1.test.ts
- packages/evm/bindings/build.rs
- packages/evm/package.json
- packages/evm/source/index.ts
- packages/test-framework/package.json
- packages/test-framework/source/factories/factories/generate-app.ts
- packages/test-framework/source/factories/factories/transaction.ts
- packages/test-framework/source/factories/helpers.test.ts
- packages/test-framework/source/factories/types.ts
- packages/test-framework/source/internal/signer.test.ts
- packages/test-framework/source/internal/signer.ts
- pnpm-lock.yaml
Minimal implementation of `crypto-transaction-evm-call` to be able to interact with the EVM. It supports contract deployments and normal contract calls.
Gas and related things like log outputs are currently ignored.
> feat(crypto-transaction-evm-call): initial transaction implementation 

- packages/validator-set-vote-weighted/source/validator-set.test.ts
- packages/validator-set-vote-weighted/source/validator-set.ts
> fix(validator-set-vote-weighted): active validators is subset of registered validators

- .github/workflows/publish-develop.yml
> chore: fix publish GitHub workflow

- packages/api-evm/source/actions/call.ts
- packages/contracts/source/contracts/transactions.ts
- packages/crypto-transaction-evm-call/source/handlers/evm-call.ts
- packages/crypto-transaction-multi-payment/source/handlers/multi-payment.ts
- packages/crypto-transaction-multi-signature-registration/source/handlers/multi-signature-registration.ts
- packages/crypto-transaction-transfer/source/handlers/transfer.ts
- packages/crypto-transaction-username-registration/source/handlers/username-registration.ts
- packages/crypto-transaction-username-resignation/source/handlers/username-resignation.ts
- packages/crypto-transaction-validator-registration/source/handlers/validator-registration.ts
- packages/crypto-transaction-validator-resignation/source/handlers/validator-resignation.ts
- packages/crypto-transaction-vote/source/handlers/vote.test.ts
- packages/crypto-transaction-vote/source/handlers/vote.ts
- packages/evm-development/package.json
- packages/evm-development/source/deployer.ts
- packages/evm/source/index.ts
- packages/evm/source/instance.ts
- packages/evm/source/instances/evm.test.ts
- packages/evm/source/instances/evm.ts
- packages/evm/source/instances/index.ts
- packages/evm/source/instances/mock.ts
- packages/processor/source/transaction-processor.ts
- packages/processor/source/verifiers/verify-block-verifier.ts
- packages/transaction-pool/source/actions/apply-transaction.ts
- packages/transaction-pool/source/actions/throw-if-cannot-enter-pool.ts
- packages/transaction-pool/source/actions/verify-transaction.ts
- packages/transaction-pool/source/transaction-validator.ts
- packages/transactions/source/handlers/transaction.ts
- pnpm-lock.yaml
Include Mock EVM implementation that is used by **transaction-pool** and **collator**. We don't run TX in the EVM environment to improve performance. Mock transact method will return max gas that TX can consume and remove that value from senders balance.
> feat: create transaction handler context that provides EVM instance

- packages/crypto-transaction-multi-payment/source/versions/1.ts
- packages/crypto-transaction-multi-signature-registration/source/versions/1.ts
- packages/crypto-transaction-transfer/source/handlers/transfer.ts
- packages/crypto-transaction-transfer/source/versions/1.ts
- packages/crypto-transaction-username-registration/source/versions/1.ts
- packages/crypto-transaction-username-resignation/source/versions/1.ts
- packages/crypto-transaction-validator-registration/source/versions/1.ts
- packages/crypto-transaction-validator-resignation/source/versions/1.ts
- packages/crypto-transaction-vote/source/versions/1.ts
- packages/crypto-transaction/source/validation/schemas.test.ts
- packages/crypto-transaction/source/validation/schemas.ts
- packages/transactions/source/handlers/transaction.ts
Let a transaction handler implementation decide what to do with `amount` instead of having a blanket implementation for it to avoid conflicting updates.
> refactor(transactions): move amount deduction into transaction handlers

- packages/bootstrap/source/bootstrapper.ts
- packages/consensus/source/consensus.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/contracts/source/contracts/validator.ts
- packages/state/source/wallets/wallet.ts
- packages/validator/source/validator-repository.ts
Print loaded validators on bootstrap.
> feat(validator): log loaded validators

- packages/contracts/source/exceptions/pool.ts
- packages/fees-managed/source/matcher.ts
- packages/fees-static/source/matcher.ts
- packages/transaction-pool/source/errors.test.ts
- packages/transaction-pool/source/processor.test.ts
`to low` -> `too low`,
`to high` -> `too high`
> chore: fix typo in transaction fee errors

- packages/api/bin/run
- packages/api/source/commands/api-run.ts
- packages/api/source/commands/api-start.ts
- packages/api/source/commands/config-publish.ts
- packages/configuration-generator/source/generators/app.ts
- packages/core/source/commands/config-publish.ts
- packages/core/source/commands/core-start.ts
> fix(api): broken entrypoint

- packages/configuration-generator/bin/create-genesis-block.js
> fix(configuration-generator): create genesis block script

- packages/kernel/source/bootstrap/load-service-providers.test.ts
- packages/kernel/source/providers/plugin-manifest.test.ts
- packages/kernel/source/providers/plugin-manifest.ts
- packages/kernel/source/providers/service-provider.test.ts
Fix issue with package.json paths.
> fix(core): resolve correct plugin `package.json` path

- packages/api/source/commands/api-start.test.ts
- packages/api/source/commands/api-start.ts
- packages/cli/source/application-factory.ts
- packages/cli/source/contracts.ts
- packages/cli/source/ioc/identifiers.ts
- packages/cli/source/services/index.ts
- packages/cli/source/services/setup.ts
- packages/core/source/commands/core-start.test.ts
- packages/core/source/commands/core-start.ts
Add `Setup` class. Determine global or local setup and use correct paths.
> feat(cli): determine correct entrypoint paths

- packages/api-database/source/contracts.ts
- packages/api-database/source/repositories/transaction-repository.ts
- packages/api-http/integration/routes/node.test.ts
- packages/api-http/source/controllers/node.ts
> fix(api-http): exclude genesis transactions from fee statistics calculation

- scripts/install-alpha.sh
- Fix - paths according to the latest naming convention.
> fix: use paths according to the latest naming convention in `install-alpha.sh`script

- packages/configuration-generator/source/generators/milestones.test.ts
- packages/configuration-generator/source/generators/milestones.ts
> fix(configuration-generator): milestone generator add static fees

- packages/test-runner/source/hooks.test.ts
- packages/test-runner/source/hooks.ts
> fix(test-runner): rethrow error in runHook

- packages/kernel/source/application.ts
- packages/kernel/source/bootstrap/index.ts
- packages/kernel/source/bootstrap/listen-to-shutdown-signals.ts
Move logic from app to bootstrap class.
> refactor(kernel): create bootstraper for shutdown signals 

- tests/functional/transaction-pool-api/source/utils.ts
- tests/functional/transaction-pool-api/source/vote.test.ts
> test(functional/transaction-pool): increase vote coverage

- tests/functional/transaction-pool-api/source/utils.ts
- tests/functional/transaction-pool-api/source/validator-resignation.test.ts
- tests/functional/transaction-pool-api/source/vote.test.ts
> test(functional/transaction-pool): increase validator resignation coverage

- tests/functional/transaction-pool-api/source/username-registration.test.ts
- tests/functional/transaction-pool-api/source/utils.ts
- tests/functional/transaction-pool-api/source/vote.test.ts
> test(functional/transaction-pool): increase username registration coverage

- packages/crypto-transaction-username-resignation/source/handlers/username-resignation.ts
- tests/functional/transaction-pool-api/source/username-resignation.test.ts
- tests/functional/transaction-pool-api/source/utils.ts
- tests/functional/transaction-pool-api/source/vote.test.ts
> test(functional/transaction-pool): increase username resignation coverage

- packages/kernel/source/utils/is-majority.test.ts
- packages/kernel/source/utils/is-majority.ts
- packages/kernel/source/utils/is-minority.test.ts
- packages/kernel/source/utils/is-minority.ts
- packages/kernel/test/fixtures/active-validators.ts
> fix(kernel): minority and majority calculation

- packages/api-http/source/schemas/wallets.ts
> fix(api-http): allow 0 nonce in schema

- packages/crypto-transaction-multi-signature-registration/source/versions/1.ts
- tests/functional/transaction-pool-api/source/multi-signature-registration.test.ts
- tests/functional/transaction-pool-api/source/setup.ts
- tests/functional/transaction-pool-api/source/utils.ts
- tests/functional/transaction-pool-api/source/verifier.ts
> test(functional/transaction-pool): increase multi sig registration coverage 

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/kernel/source/enums/events.ts
> feat(consensus): emit events

- packages/p2p/source/socket-server/plugins/codec.ts
Help determining codec issues.
> refactor(p2p): log route on codec error

- .gitignore
> test(functional/transaction-pool): add .gitkeep

- .eslintrc.js
- tests/functional/consensus/source/asserts.ts
- tests/functional/consensus/source/p2p.ts
- tests/functional/consensus/source/precommit.test.ts
- tests/functional/consensus/source/prevote.test.ts
- tests/functional/consensus/source/propose.test.ts
- tests/functional/consensus/source/utils.ts
- tests/functional/consensus/source/worker.ts
Test various scenarios for prevote & precommit:
- missing messages
- null messages
- fake blockId
- missing messages & malicious messages
> test(functional/consensus): test prevote & precommit scenarios

- packages/configuration-generator/bin/create-genesis-block.js
> fix(configuration-generator): update export paths

- packages/api-development/package.json
- packages/api-development/source/controllers/peers.ts
- packages/api-development/source/resources/banned-peer.ts
- packages/api-development/source/resources/index.ts
- packages/api-development/source/routes/peers.ts
- packages/contracts/source/contracts/p2p/peer-disposer.ts
- packages/p2p/source/peer-disposer.ts
- pnpm-lock.yaml
> feat(api-development): add `peers/banned` endpoint

- .github/workflows/functional.yml
> test(functional): update ci workflow

- packages/consensus-storage/package.json
- packages/consensus-storage/source/service.ts
- packages/database/package.json
- packages/database/source/database-service.ts
- pnpm-lock.yaml
- Update lmdb version. 
- Include errors
- Wait until flushed
> deps: update lmdb

- tests/functional/transaction-pool-api/source/setup.ts
> test(functional): fix `MaxListenersExceeded` warning

- packages/contracts/source/contracts/p2p/peer-disposer.ts
- packages/p2p/source/defaults.ts
- packages/p2p/source/header-service.ts
- packages/p2p/source/peer-disposer.ts
- packages/p2p/source/peer-verifier.ts
- packages/p2p/source/socket-server/plugins/base-plugin.ts
- packages/p2p/source/socket-server/plugins/validate-data.test.ts
- packages/p2p/source/socket-server/plugins/validate-data.ts
- packages/p2p/source/socket-server/plugins/validate-ip.ts
- packages/p2p/source/socket-server/plugins/validate.ts
- packages/p2p/source/socket-server/server.ts
- Ban peer even if it not in the repo
- Separate verification plugins for data and IP
- Skip header check if peer is not in repo (might be banned)
> fix(p2p): peer ban and validate ip plugin

- packages/cli/source/component-factory.ts
- packages/core/source/commands/config-publish-custom.ts
> feat(cli): add --overwrite flag to `config:publish:custom`

- packages/p2p/source/reply-schemas/post-transactions.test.ts
- packages/p2p/source/reply-schemas/post-transactions.ts
- packages/p2p/source/socket-server/codecs/proto/post-transactions.proto
- packages/p2p/source/socket-server/codecs/proto/protos.d.ts
- packages/p2p/source/socket-server/codecs/proto/protos.js
Transaction responses was changed from string to number. Change is introduced:  #483
> fix(p2p): postTransactions response schema and proto

- packages/api-common/source/plugins/pagination/extension.ts
> refactor(api): show `meta` field in response at top

- packages/api-database/source/repositories/wallet-repository.ts
- packages/api-http/integration/routes/delegates.test.ts
> fix(api-http): change default sort for `/delegates`

- packages/processor/source/block-processor.ts
> refactor(block-processor): log commit round

- packages/consensus/source/processors/proposal-processor.ts
Improve performance on very big blocks (>1MB). Verification delay si reduced from  ~500ms to ~5ms.
> perf(consensus): verify proposal signatures on main thread

- packages/consensus/source/processors/proposal-processor.ts
Remove hasValidBlockGenerator check. #378 implements this check on block processor.
> refactor(consensus): remove hasValidBlockGenerator check

- packages/api-database/source/repositories/wallet-repository.ts
- packages/api-http/integration/routes/delegates.test.ts
> fix(api-http): sort delegates by rank asc by default

- packages/consensus/source/consensus.ts
Run pending rounds only once. Skip handle if pending RoundState is already exists.
> perf(consensus): run pending RoundStates only once

- pnpm-lock.yaml
https://github.com/pnpm/pnpm/releases/tag/v9.0.0
> chore: upgrade pnpm v9

- packages/webhooks/source/listener.test.ts
- packages/webhooks/source/listener.ts
> feat(webhooks): support nested key conditions

- tests/functional/transaction-pool-api/paths/config/crypto.json
- tests/functional/transaction-pool-api/source/setup.ts
- tests/functional/transaction-pool-api/source/utils.ts
> test(functional/transaction-pool): improve intermittent failures caused by flaky tests

- .github/workflows/check-commit-count.yml
> chore(ci): add workflow to enforce minimum commit count

- packages/api-sync/source/service.ts
> fix(api-sync): upsert version on bootstrap

- packages/api-sync/package.json
- packages/api-sync/source/defaults.ts
- packages/api-sync/source/listeners/abstract-listener.ts
- packages/api-sync/source/listeners/api-nodes.ts
- packages/api-sync/source/listeners/mempool.ts
- packages/api-sync/source/listeners/peers.ts
- packages/api-sync/source/listeners/plugins.ts
- packages/api-sync/source/service-provider.ts
- pnpm-lock.yaml
Add syncInterval option in default instead using block time.
> refactor(api-sync): add `syncInterval` option

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/consensus/source/scheduler.test.ts
- packages/consensus/source/scheduler.ts
- packages/contracts/source/contracts/consensus/consensus.ts
- packages/contracts/source/contracts/validator.ts
- packages/test-transaction-builders/source/utils.ts
- packages/validator/package.json
- packages/validator/source/validator.ts
- pnpm-lock.yaml
- tests/functional/consensus/source/custom-proposal.ts
- tests/functional/consensus/source/precommit.test.ts
- tests/functional/consensus/source/prevote.test.ts
- tests/functional/consensus/source/propose-invalid.test.ts
- tests/functional/consensus/source/propose.test.ts
- tests/functional/consensus/source/utils.ts
Prepare block before starting new round.
> refactor(consensus): prepare block after commit

- packages/consensus/source/consensus.test.ts
- packages/consensus/source/consensus.ts
- packages/consensus/source/scheduler.test.ts
- packages/consensus/source/scheduler.ts
- packages/contracts/source/contracts/consensus/consensus.ts
Emit *any event only once. It is based on scheduler timeout status.
> refactor(consensus):  dispatch *any events only once per round

- packages/contracts/source/contracts/state/repository.ts
- packages/contracts/source/contracts/state/store.ts
- packages/contracts/source/contracts/state/wallets.ts
- packages/contracts/source/contracts/transaction-pool/client.ts
- packages/processor/source/block-processor.ts
- packages/state/source/repository.ts
- packages/state/source/store.ts
- packages/state/source/wallets/wallet-repository-clone.ts
- packages/state/source/wallets/wallet-repository.ts
- packages/state/source/wallets/wallet.ts
- packages/transaction-pool-client/source/client.ts
- packages/transaction-pool-server/source/actions/commit.ts
- packages/transaction-pool-server/source/actions/index.ts
- packages/transaction-pool-server/source/service-provider.ts
- tests/functional/consensus/source/setup.ts
Export & import changes.
Sync changes from client to server.
> feat(state): supports state sync using delta changes

- packages/contracts/source/contracts/crypto/transactions.ts
- packages/crypto-transaction/source/builders.ts
- packages/crypto-transaction/source/types/transaction.ts
> refactor(crypto-transaction): make `id` mandatory

- packages/processor/source/block-processor.ts
- packages/transaction-pool-client/source/client.ts
- packages/transaction-pool-server/source/actions/commit.ts
- packages/transaction-pool-server/source/routes/base.ts
> feat(transaction-pool): sync block and transactions

- packages/evm/Cargo.lock
- packages/evm/bindings/src/ctx.rs
- packages/evm/bindings/src/lib.rs
- packages/evm/core/Cargo.toml
- packages/evm/core/src/constants.rs
- packages/evm/core/src/db.rs
- packages/evm/core/src/lib.rs
- packages/evm/core/src/state_changes.rs
- packages/evm/source/instances/evm.test.ts
> perf(evm): refactor state persistence

- packages/api-http/integration/routes/validator-rounds.test.ts
- packages/api-http/source/controllers/validator-rounds.ts
- packages/api-http/source/routes/validator-rounds.ts
> feat(api-http): query round by number

- packages/bootstrap/source/bootstrapper.ts
- packages/contracts/source/contracts/state/service.ts
- packages/contracts/source/contracts/state/snapshots.ts
- packages/contracts/source/contracts/transaction-pool/client.ts
- packages/contracts/source/identifiers.ts
- packages/state/source/defaults.ts
- packages/state/source/service-provider.ts
- packages/state/source/service.ts
- packages/state/source/snapshots/exporter.ts
- packages/state/source/snapshots/importer.ts
- packages/state/source/snapshots/index.ts
- packages/state/source/snapshots/snapshot-service.ts
- packages/transaction-pool-client/source/client.ts
- packages/transaction-pool-server/source/actions/commit.ts
- packages/transaction-pool-server/source/actions/import-snapshot.ts
- packages/transaction-pool-server/source/actions/index.ts
- packages/transaction-pool-server/source/actions/list-snapshots.ts
- packages/transaction-pool-server/source/service-provider.ts
> feat(transaction-pool): list & import snapshots

- packages/contracts/source/exceptions/crypto.ts
- packages/crypto-transaction-validator-registration/source/handlers/validator-registration.test.bkp
- packages/crypto-transaction-validator-registration/source/handlers/validator-registration.ts
- packages/test-transaction-builders/source/validator-registrations.ts
- tests/functional/transaction-pool-api/source/validator-registration.test.ts
- tests/functional/transaction-pool-api/source/validator-resignation.test.ts
> feat(crypto-transaction-validator-registration): accept registration from multisig wallet

- packages/evm/core/src/db.rs
- packages/evm/source/instances/evm.ts
> refactor(evm): set NO_SUB_DIR flag

- .github/workflows/e2e.yml
- packages/bootstrap/source/bootstrapper.ts
- packages/contracts/source/contracts/transaction-pool/client.ts
- packages/transaction-pool-client/source/client.ts
- packages/transaction-pool-server/source/actions/get-status.ts
- packages/transaction-pool-server/source/actions/import-snapshot.ts
- packages/transaction-pool-server/source/actions/index.ts
- packages/transaction-pool-server/source/service-provider.ts
> feat(transaction-pool): implement `get_status` JSON_RCP endpoint

- packages/api-common/source/validation/schemas.ts
- packages/contracts/source/contracts/transaction-pool/actions.ts
- packages/contracts/source/contracts/transaction-pool/index.ts
- packages/transaction-pool-client/source/client.ts
- packages/transaction-pool-client/source/reply-schemas.ts
- packages/transaction-pool-server/source/actions/commit.ts
- packages/transaction-pool-server/source/actions/get-status.ts
- packages/transaction-pool-server/source/actions/get-transactions.ts
- packages/transaction-pool-server/source/actions/import-snapshot.ts
- packages/transaction-pool-server/source/actions/list-snapshots.ts
Add  request and response schemas for JSON_RPC actions
> feat(transaction-pool): add  request and response schemas for JSON_RPC actions

- packages/bootstrap/source/bootstrapper.ts
- packages/state/source/service.ts
Recreate state on snapshot restore.
> refactor(state): recreate state on snapshot restore

- packages/api-sync/source/service.ts
> fix(api-sync): make bootstrap less verbose

- packages/kernel/source/bootstrap/load-service-providers.ts
> fix(transaction-pool-worker): update local module import workaround

- packages/bootstrap/source/bootstrapper.ts
- packages/core/bin/config/testnet/core/app.json
- packages/state/source/service.ts
- packages/transaction-pool-worker/source/service-provider.ts
Make client mandatory and disable snapshot export on transaction-pool worker.
> refactor(transaction-pool): disable snapshot export

- .github/workflows/e2e.yml
- packages/p2p/source/socket-server/server.ts
- packages/p2p/source/socket-server/utils/get-peer-config.ts
- tests/e2e/consensus/checks/Dockerfile
- tests/e2e/consensus/nodes/node0/core/app.json
- tests/e2e/consensus/nodes/node1/core/app.json
- tests/e2e/consensus/nodes/node2/core/app.json
> test(ci): fix e2e tests

- packages/contracts/source/contracts/evm/evm.ts
- packages/crypto-transaction-evm-call/source/handlers/evm-call.ts
- packages/evm/source/index.ts
- packages/evm/source/instances/ephemeral.ts
- packages/evm/source/instances/evm.ts
- packages/evm/source/instances/index.ts
- packages/evm/source/instances/mock.ts
- packages/transactions/source/transaction-validator.ts
- tests/functional/transaction-pool-api/source/snapshot.ts
> refactor(evm): use ephemeral evm for transaction validator instead of a cache

- packages/contracts/source/contracts/evm/evm.ts
- packages/crypto-transaction-evm-call/source/handlers/evm-call.ts
- packages/evm-development/source/deployer.ts
- packages/evm/bindings/src/ctx.rs
- packages/evm/bindings/src/lib.rs
- packages/evm/bindings/src/result.rs
- packages/evm/core/src/db.rs
- packages/evm/source/instances/evm.test.ts
> feat(evm): store commit receipts

- packages/api-database/source/contracts.ts
- packages/api-database/source/identifiers.ts
- packages/api-database/source/models/index.ts
- packages/api-database/source/models/receipt.ts
- packages/api-database/source/repositories/index.ts
- packages/api-database/source/repositories/receipt-repository.ts
- packages/api-database/source/service-provider.ts
- packages/api-sync/source/service.ts
- packages/bootstrap/source/bootstrapper.ts
- packages/consensus/source/consensus.ts
- packages/contracts/source/contracts/processor.ts
- packages/contracts/source/contracts/transactions.ts
- packages/crypto-transaction-evm-call/source/handlers/evm-call.ts
- packages/processor/source/block-processor.ts
- packages/processor/source/transaction-processor.ts
- packages/transactions/source/handlers/transaction.ts
> feat(evm): sync receipts to postgres

- packages/bootstrap/source/bootstrapper.ts
> fix(bootstrap): set processor result on commit state

- packages/api-database/source/contracts.ts
- packages/api-database/source/migrations/1697617471901-CreateIndexes.ts
- packages/api-database/source/models/receipt.ts
- packages/api-database/source/repositories/receipt-repository.ts
- packages/api-database/source/repositories/transaction-repository.ts
- packages/api-database/source/repositories/wallet-repository.ts
- packages/api-database/source/search/criteria.ts
- packages/api-database/source/search/filters/index.ts
- packages/api-database/source/search/filters/receipt-filter.ts
- packages/api-database/source/transformers/buffer.ts
- packages/api-http/integration/routes/receipts.test.ts
- packages/api-http/source/controllers/blocks.ts
- packages/api-http/source/controllers/delegates.ts
- packages/api-http/source/controllers/receipts.ts
- packages/api-http/source/controllers/transactions.ts
- packages/api-http/source/controllers/votes.ts
- packages/api-http/source/controllers/wallets.ts
- packages/api-http/source/handlers.ts
- packages/api-http/source/resources/index.ts
- packages/api-http/source/resources/receipt.ts
- packages/api-http/source/routes/receipts.ts
- packages/api-http/test/fixtures/receipts.json
- packages/api-http/test/helpers/prepare-sandbox.ts
- packages/api-sync/source/service.ts
Add basic `/receipts` endpoint to query tx receipts stored in postgres.
> feat(evm): add `/receipts` endpoint

- packages/p2p/source/peer-communicator.ts
> refactor(p2p): increase timeouts

- packages/transaction-pool-worker/source/handlers/commit.ts
> refactor(transaction-pool-worker): remove extra logs

- packages/bootstrap/source/bootstrapper.ts
- packages/contracts/source/contracts/transaction-pool/worker.ts
- packages/transaction-pool-service/source/service.ts
- packages/transaction-pool-worker/source/handlers/commit.ts
- packages/transaction-pool-worker/source/handlers/index.ts
- packages/transaction-pool-worker/source/handlers/start.ts
- packages/transaction-pool-worker/source/worker-handler.ts
- packages/transaction-pool-worker/source/worker.ts
- tests/functional/transaction-pool-api/source/pool-worker.ts
- ReAdd transaction on boot & milestone change
- Clear transactions on block
> refactor(transaction-pool-service): readd transactions on boot and milestone change

- packages/evm/bindings/src/lib.rs
- packages/evm/core/src/db.rs
- packages/evm/core/src/lib.rs
- packages/evm/core/src/state_commit.rs
> feat(evm): resize db dynamically

- packages/evm/Cargo.lock
- packages/evm/Cargo.toml
- packages/evm/core/src/db.rs
- packages/evm/core/src/state_changes.rs
> chore(evm): upgrade to latest `revm`

- .github/workflows/deps.yml
- .github/workflows/e2e.yml
- .github/workflows/functional.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/publish-develop.yml
- .github/workflows/unit.yml
- scripts/generate-unit-workflow.js
Fix deprecation warning:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, pnpm/action-setup@v2, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> chore(ci): fix deprecation warning

- packages/contracts/source/contracts/transactions.ts
- packages/crypto-transaction-validator-registration/source/handlers/validator-registration.ts
- packages/crypto-transaction-validator-resignation/source/handlers/validator-resignation.ts
- packages/crypto-transaction-vote/source/handlers/vote.test.ts
- packages/crypto-transaction-vote/source/handlers/vote.ts
- packages/processor/source/block-processor.ts
- packages/transactions/source/handlers/handler-registry.test.ts
- packages/transactions/source/handlers/transaction.ts
> refactor(transactions): inject EventDispatcher

- .github/workflows/e2e.yml
- tests/e2e/consensus/nodes/node0/core/crypto.json
- tests/e2e/consensus/nodes/node0/core/validators.json
- tests/e2e/consensus/nodes/node1/core/crypto.json
- tests/e2e/consensus/nodes/node1/core/validators.json
- tests/e2e/consensus/nodes/node2/core/crypto.json
- tests/e2e/consensus/nodes/node2/core/validators.json
- tests/e2e/consensus/nodes/node3/core/crypto.json
- tests/e2e/consensus/nodes/node3/core/validators.json
- tests/e2e/consensus/nodes/node4/core/crypto.json
- tests/e2e/consensus/nodes/node4/core/validators.json
Generate new configuration and enable tests.
> test(e2e): generate configuration 

- packages/state/source/defaults.ts
> refactor(state): increase default export interval
