packages/configuration-generator/source/generators/milestones.test.ts
packages/configuration-generator/source/generators/milestones.ts
packages/consensus/source/scheduler.test.ts
packages/consensus/source/scheduler.ts
packages/contracts/source/contracts/crypto/networks.ts
packages/core/bin/config/testnet/crypto.json
packages/crypto-config/source/configuration.test.ts

Add new milestone entries:
- stageTimeout -> represent default stage timeout value
- stageTimeoutIncrease -> represent timeout increase per each round
Changes:
- add values to milestones
- fix configuration-generator
- use values in consensus `Scheduler`

feat:  introduce `stageTimeout` & `stageTimeoutIncrease` milestone entries

---

packages/contracts/source/contracts/state/wallets.ts
packages/state/source/block-state.ts
packages/state/source/dpos/dpos.test.ts
packages/state/source/round-state.ts
packages/state/source/wallets/indexers/indexers.ts
packages/state/source/wallets/wallet-holder.test.ts
packages/state/source/wallets/wallet-holder.ts
packages/state/source/wallets/wallet-index.test.ts
packages/state/source/wallets/wallet-index.ts
packages/state/source/wallets/wallet-repository-clone.test.ts
packages/state/source/wallets/wallet-repository-clone.ts
packages/state/source/wallets/wallet-repository-copy-on-write.test.ts
packages/state/source/wallets/wallet-repository-copy-on-write.ts
packages/state/source/wallets/wallet-repository.test.ts
packages/state/source/wallets/wallet-repository.ts
packages/state/test/build-validator-and-vote-balances.ts

Use **WalletHolder** to support wallet merging. 
Remove wallet create method. Use **findByAddress** and **findByPublicKey** to create wallet. 
Simplify WalletRepositoryClone.

refactor(state): implement `WalletHolder` and remove `walletCreate` method 

---

packages/contracts/source/contracts/crypto/block.ts
packages/crypto-block/source/id.factory.ts
packages/crypto-block/source/serializer.ts
packages/database/source/database-service.test.ts
packages/database/source/database-service.ts
packages/p2p/source/peer-verifier.ts
packages/processor/source/handlers/exception-handler.ts
packages/state/source/stores/state.ts

The `id` and `transactions` fields of `IBlockData` and `IBlockJson` are now mandatory. Also get rid of some obsolete asserts.

refactor(crypto): make block id and transactions mandatory

---

packages/contracts/source/contracts/transactions.ts
packages/crypto-transaction-multi-payment/source/handlers/multi-payment.ts
packages/crypto-transaction-multi-signature-registration/source/handlers/multi-signature-registration.ts
packages/crypto-transaction-transfer/source/handlers/transfer.ts
packages/crypto-transaction-validator-registration/source/handlers/validator-registration.ts
packages/crypto-transaction-validator-resignation/source/handlers/validator-resignation.ts
packages/crypto-transaction-vote/source/handlers/vote.test.ts
packages/crypto-transaction-vote/source/handlers/vote.ts
packages/fees-burn/source/mutator.ts
packages/processor/source/block-processor.ts
packages/state/source/block-state.ts
packages/state/source/database-interactions.ts
packages/state/source/mutators/balance.ts
packages/state/source/state-builder.ts
packages/state/source/transaction-validator.ts
packages/state/test/setup.ts
packages/transaction-pool/source/actions/apply-transaction.ts
packages/transaction-pool/source/actions/revert-transaction.ts
packages/transaction-pool/source/actions/throw-if-cannot-enter-pool.ts
packages/transaction-pool/source/actions/verify-transaction.ts
packages/transaction-pool/source/sender-state.test.ts
packages/transaction-pool/source/sender-state.ts
packages/transactions/source/handlers/transaction.ts

Pass WalletRepostiory instance directly to TransactionHandler methods.

refactor: pass WalletRepostiory instance to TransactionHandler methods

---

packages/consensus/source/consensus.ts
packages/consensus/source/handler.ts
packages/consensus/source/round-state.ts
packages/contracts/source/contracts/consensus.ts

Use RoundState as central object to hold block, walletRepostiory and processor result. 
Process block on proposal. 
For each instance of RoundState new WalletRepostioryClone is created.

refactor(consensus): use `RoundState` as block, walletRespository and processor result holder

---

packages/utils/source/big-number.ts

Use private keyword insted #prefix for value, to support BigNumber clone. 
Temporary fixes issue when cloning wallet attributes. 
Example: validator.voteBalance

fix(utils): use private keyword on BigNumber to support cloning

---

packages/consensus/source/consensus.ts
packages/consensus/source/handler.ts
packages/consensus/source/round-state-repository.ts
packages/consensus/source/round-state.ts
packages/consensus/source/types.ts
packages/contracts/source/contracts/consensus.ts
packages/validator-set-static/source/index.ts

Improve message handling:
- Accept only one message per validator
- Call consensus only when accepted 
- Count messages and support for different ids 
Other:
- Call all consensus methods
- Set validators on round creation
- Add contracts

feat(consensus): extended message handling 

---

packages/contracts/source/contracts/crypto/block.ts
packages/contracts/source/index.ts
packages/contracts/source/utils.ts
packages/crypto-block/source/deserializer.ts
packages/crypto-block/source/factory.ts
packages/crypto-block/source/verifier.ts

Make interfaces readonly. Introduce Mutable TS util, that makes readonly fields on object mutable.

refactor(contracts): make Block interfaces readonly

---

packages/contracts/source/contracts/crypto/messages.ts
packages/crypto-messages/source/deserializer.ts
packages/crypto-messages/source/factory.test.ts
packages/crypto-messages/source/factory.ts
packages/crypto-messages/source/precommit.test.ts
packages/crypto-messages/source/precommit.ts
packages/crypto-messages/source/prevote.test.ts
packages/crypto-messages/source/prevote.ts
packages/crypto-messages/source/serializer.ts
packages/crypto-messages/test/helpers/prepare-sandbox.ts
packages/p2p/source/socket-server/controllers/post-precommit.test.ts
packages/p2p/source/socket-server/controllers/post-precommit.ts
packages/p2p/source/socket-server/controllers/post-prevote.test.ts
packages/p2p/source/socket-server/controllers/post-prevote.ts
packages/p2p/source/socket-server/controllers/post-proposal.test.ts
packages/p2p/source/socket-server/controllers/post-proposal.ts
packages/p2p/source/socket-server/server.test.ts
packages/serializer/source/serializer.ts

- use tagged values directly on serializer object instead on injects
- use consenusSignature type on crypto-messages
- extend factory with* fromBytes methods
- use proper types 
- use factory instead deserialzier on p2p

fix: crypto messages serialization and deserialziation issues

---

packages/consensus/source/consensus.test.ts
packages/consensus/source/consensus.ts
packages/consensus/source/enums.ts
packages/contracts/source/contracts/consensus.ts
packages/contracts/source/contracts/crypto/enums.ts

refactor(consensus): move enums to contracts

---

packages/blockchain/source/state-machine/actions/initialize.ts
packages/consensus/source/consensus.ts
packages/consensus/source/scheduler.ts
packages/contracts/source/contracts/consensus.ts

Implements delayed start. It is mainly used for **testing purposes**.
Nodes start consensus on every full 30 second interval.

feat(consensus): delayed start

---

packages/validation/package.json
packages/validation/source/validator.ts
pnpm-lock.yaml

Add formats defined in [ajv-formats ](https://github.com/ajv-validator/ajv-formats)package. Formats are added to support: ipv4 and ipv6 in p2p reply schemas.

feat(validators): add formats

---

packages/contracts/source/contracts/p2p/endpoints.ts
packages/contracts/source/contracts/p2p/header-service.ts
packages/contracts/source/contracts/p2p/header.ts
packages/contracts/source/contracts/p2p/index.ts
packages/contracts/source/contracts/p2p/peer-repository.ts
packages/contracts/source/contracts/p2p/peer.ts
packages/contracts/source/identifiers.ts
packages/p2p/source/block-downloader.ts
packages/p2p/source/constants.ts
packages/p2p/source/downloader.ts
packages/p2p/source/header-service.ts
packages/p2p/source/header.ts
packages/p2p/source/peer-communicator.ts
packages/p2p/source/peer-discoverer.ts
packages/p2p/source/peer-repository.ts
packages/p2p/source/service-provider.ts
packages/p2p/source/socket-server/plugins/header-handle.ts
packages/p2p/source/socket-server/plugins/header-include.ts
packages/p2p/source/socket-server/server.test.ts

- Temporary limit the download to one concurrent download per time. Prevote & precommit downloading will be improved in the future.
- Check peer header after delay, because new headers are expected in short time for precommit and prevote messages. 
- Skip header check if one is already pending for a peer.

feat(p2p): limit downloads

---

packages/contracts/source/contracts/p2p/peer-connector.ts
packages/p2p/source/hapi-nes/client.ts
packages/p2p/source/peer-communicator.ts
packages/p2p/source/peer-connector.ts

Remove setMaxPayload method, because it is overwritten on request and it doesn't handle payload restrictions properly. This results in server disconnection when, because payload is exceeded, when lover value is set by another request. The collision is more often when the number of peer is low and traffic is high.

refactor(p2p): remove `setMaxPayload` method form websocket client

---

packages/p2p/source/block-downloader.ts
packages/p2p/source/socket-server/controllers/get-blocks.test.ts
packages/p2p/source/socket-server/controllers/get-blocks.ts
packages/p2p/source/socket-server/routes/route.ts
packages/p2p/source/socket-server/schemas/get-blocks.ts
packages/p2p/source/utils/build-rate-limiter.ts

- use correct limit values
- improve getBlocks validation schema
- validate route payload

fix(p2p): getBlocks limit parameter

---

packages/contracts/source/contracts/crypto/messages.ts
packages/crypto-messages/source/factory.ts
packages/crypto-messages/source/precommit.test.ts
packages/crypto-messages/source/precommit.ts
packages/crypto-messages/source/prevote.test.ts
packages/crypto-messages/source/prevote.ts
packages/crypto-messages/source/proposal.test.ts
packages/crypto-messages/source/proposal.ts
packages/p2p/source/broadcaster.ts
packages/p2p/source/socket-server/controllers/get-messages.ts
packages/p2p/source/socket-server/controllers/get-proposal.ts

Add a `serialized` field to the message objects to keep the original bytes around, so we don't have to serialize them again for p2p gossip.

refactor(crypto-messages): add serialized field

---

packages/crypto-messages/source/keywords.test.ts
packages/crypto-messages/source/keywords.ts
packages/crypto-messages/source/schemas.test.ts
packages/crypto-messages/source/schemas.ts
packages/p2p/source/reply-schemas/get-messages.test.ts
packages/p2p/source/reply-schemas/get-messages.ts
packages/p2p/source/reply-schemas/headers.ts
packages/p2p/test/helpers/prepare-validator-context.ts

Implement and uses **limitToActiveValidators** keyword.  **isValidatorBitmap** is removed.

refactor(crypto-messages): implements `limitToActiveValidators` keyword

---

packages/consensus/source/consensus.test.ts
packages/consensus/source/consensus.ts
packages/consensus/source/round-state-repository.ts
packages/consensus/source/storage.ts
packages/contracts/source/contracts/consensus/consensus.ts

Support multiple messages per validator per height for different rounds to cover scenarios where network fragmentation may lead to a validator proposing multiple times per height.
Also fix a potential "memory leak" caused by the round state repository keeping old heights in memory.

refactor(consensus): store messages by validator and round

---

packages/consensus/source/consensus.test.ts
packages/consensus/source/consensus.ts

Clean roundStateRepository and storage only on commit instead when height is 0. This prevents unintended data loss, when bootstrapping round 0.

fix(consenus): clean on commit

---

packages/consensus/source/committed-block-state.ts
packages/consensus/source/consensus.test.ts
packages/consensus/source/consensus.ts
packages/consensus/source/round-state.ts
packages/contracts/source/contracts/block-processor.ts

Rerun all round states on bootstrap after the last one. There is a case where +2/3 precommits are received and that can be for the any round.  
Additionally block processor is called  from the handle method, so consensus methods always work with the checked block.

fix(consensus): rerun all roundStates on bootstrap & process block on handle

---

packages/consensus/source/consensus.test.ts
packages/consensus/source/consensus.ts
packages/consensus/source/index.ts
packages/consensus/source/processors/abstract-processor.ts
packages/consensus/source/processors/committed-block-processor.ts
packages/consensus/source/processors/precommit-processor.ts
packages/consensus/source/processors/prevote-processor.ts
packages/consensus/source/processors/proposal-processor.ts
packages/contracts/source/contracts/kernel/index.ts
packages/contracts/source/contracts/kernel/lock.ts
packages/contracts/source/identifiers.ts
packages/kernel/source/utils/lock.ts

Commit lock is used by the message processors. It is there to ensure data consistency, meaning that processing should be atomic and executed between the commits. 
We must ensure that all commit changes are executed before we process, otherwise we can get into the situation when height is increased, but the validator set is not updated yet. This can lead to the invalid check in the processors.

feat(consensus): implements `commit` lock

---

packages/p2p/source/peer-verifier.ts

Fix verifier. Await response before accessing array item.

fix(p2p): await response before accessing array item in verifier 

---

packages/consensus/source/proposer-picker.test.ts
packages/consensus/source/proposer-picker.ts
packages/processor/source/block-processor.ts
packages/state/source/stores/state.ts

Don't use current round, but only last committed round to calculate seed.

fix(consensus): ProposerPicker seed calculation 

---

packages/contracts/source/contracts/kernel/log.ts
packages/kernel/source/application.ts
packages/kernel/source/services/log/drivers/memory.ts
packages/logger-pino/source/driver.ts

Use `string` instead of `any` in logger interface and class.

refactor(logger): use `string` instead of `any`

---

packages/bootstrap/source/bootstrapper.ts
packages/contracts/source/contracts/p2p/peer-discoverer.ts
packages/contracts/source/contracts/p2p/server.ts
packages/p2p/source/peer-discoverer.ts
packages/p2p/source/peer-processor.ts
packages/p2p/source/service-provider.test.ts
packages/p2p/source/service-provider.ts
packages/p2p/source/service.ts
packages/p2p/source/socket-server/server.ts

Refactor PeerDiscoverer. Boot p2p server after the bootstrap process. Move peer discovery and ping peer ports into PeerProcessor.

refactor(p2p): discover peers and ping ports when new peer is accepted 

---

packages/core/source/commands/core-log.ts
packages/core/source/commands/core-restart.test.ts
packages/core/source/commands/core-restart.ts
packages/core/source/commands/core-run.ts
packages/core/source/commands/core-start.ts
packages/core/source/commands/core-status.test.ts
packages/core/source/commands/core-status.ts

Technically, `token` and `network` are required for all `core:*` commands, however the schema didn't enforce it which produced weird error messages when either was absent.
Before:
```shell
pnpm run mainsail core:run
[ERROR] Expected string, got undefined
 ELIFECYCLE  Command failed with exit code 1.
```
After:
```shell
pnpm run mainsail core:run
[ERROR] "token" is required
 ELIFECYCLE  Command failed with exit code 1.
```

fix(core): make `token` / `network` command flags required

---

packages/api-database/source/models/transaction.ts

Some transactions don't have a `recipientId` (e.g. validator registrations) and fail to insert. We can consider changing this in the future.

fix(api-database): make transaction recipientId nullable

---

packages/contracts/source/contracts/state/wallets.ts
packages/state/source/wallets/wallet-index.test.ts
packages/state/source/wallets/wallet-index.ts
packages/state/source/wallets/wallet-repository-clone.ts
packages/state/source/wallets/wallet-repository-copy-on-write.ts
packages/state/source/wallets/wallet-repository.test.ts
packages/state/source/wallets/wallet-repository.ts
packages/state/source/wallets/wallet.ts

Don't clone all the indexes on wallet clone. Only difference between original index and clone index are calculated. If wallet by index exists only on original wallet repository then wallet is cloned and set to the address index. Only new sets and forgets on indexes are stored. 
Indexes are now KV (key-value) objects and doesn't store keysByWallet attributes anymore.
ForgetWallet and reset methods are removed.

refactor(state): improve wallet indexing 

---

packages/contracts/source/contracts/p2p/peer-connector.ts
packages/p2p/source/peer-communicator.ts
packages/p2p/source/peer-connector.ts
packages/p2p/source/peer-disposer.ts

Disconnect peers that are not verified and are not yet in the peers repository. Remove errors from connector and refactor.

fix(p2p): disconnect peer even if it is not in repository

---

packages/crypto-transaction-multi-payment/source/versions/1.ts
packages/crypto-transaction/source/factory.ts
packages/crypto-transaction/source/types/transaction.ts
packages/crypto-validation/source/keywords.test.ts
packages/crypto-validation/source/keywords.ts
packages/transactions/source/handlers/transaction.ts

Add missing bignumber conversion for multi payments.
The original behavior does so via the bignumber schema:
https://github.com/ArkEcosystem/core/blob/d7aa24a93495663940ccd6f05f2d67c5270d79a7/packages/crypto/src/validation/keywords.ts#L92-L93
But it has drawbacks since it modifies the data and hence was removed from mainsail.
Now `fromJson()` can be reimplemented by transaction classes to cast the respective fields.

fix(crypto): multipayment bignumber conversion

---

packages/state/source/snapshots/exporter.ts
packages/state/source/snapshots/importer.ts

The importer tries to read from the export directory, which it cannot find if the exporter never ran before thus preventing the node from booting due to the resulting exception.

fix(state): ensure snapshot directory exists

---

packages/api-database/source/models/mempool-transaction.ts
packages/api-database/source/models/transaction.ts
packages/api-database/source/transformers/vendor-field.ts

Fix vendor field being returned as a buffer object:
```
"vendorField": {"type":"Buffer","data":[100,102,115,102,100,115,102,115,100,102]}
"vendorField": "dfsfdsfsdf"
```

fix(api): transform vendorfield when reading from database

---

packages/api-database/source/models/block.ts
packages/api-database/source/models/validator-round.ts
packages/api-database/source/models/wallet.ts

Before:
```
duplicate key value violates unique constraint "UQ_905a98dead19fbbf16aabdbe121"
```
After:
```
duplicate key value violates unique constraint "unique_previous_block"
```
This way you can tell right away what the actual problem is.

fix(api-database): use explicit names for unique constraints instead of generated ones

---

packages/api-database/source/models/block.ts
packages/api-database/source/models/mempool-transaction.ts
packages/api-database/source/models/transaction.ts
packages/api-database/source/models/wallet.ts
packages/api-http/source/controllers/node.ts

We keep all columns `varchar` since there's practically no benefit in doing otherwise.
The `synced` flag is now determined based on the median peer height.

chore(api): cleanup model TODOs, calculate synced flag

---

packages/api-sync/source/sync.ts

Replace usages of `save()` with `insert().orIgnore()` for blocks and transactions.
It makes local development easier since one doesn't have to reset the postgres database all the time, another added benefit is that it removes unnecessary database round trips because each `save()` always selects first before inserting.

fix(api-sync): use `insert().orIgnore()` instead of calling `save()`

---

packages/api-common/source/index.ts
packages/api-common/source/plugins/index.ts
packages/api-common/source/plugins/response-headers.ts
packages/api-common/source/service-provider.ts
packages/api-http/source/service-provider.ts
packages/api-transaction-pool/source/service-provider.ts

Allows the main process to run the `api-transaction-pool` without `api-sync` and `api-database`.

fix(api-common): register plugin only if block repository is bound to container

---

packages/crypto-address-base58/source/address.factory.test.ts
packages/crypto-address-base58/source/address.factory.ts

Needs to be the double sha256 while it was doing a single sha256.
https://en.bitcoin.it/wiki/Base58Check_encoding
For this we should use the `hash256` function which does exactly that.

fix(crypto-address-base58): checksum calculation

---

packages/contracts/source/contracts/crypto/transactions.ts
packages/crypto-signature-schnorr-legacy/source/index.ts
packages/crypto-signature-schnorr/source/index.ts
packages/crypto-transaction-multi-payment/source/versions/1.ts
packages/crypto-transaction-multi-signature-registration/source/versions/1.ts
packages/crypto-transaction-transfer/source/versions/1.ts
packages/crypto-transaction-username-registration/source/versions/1.ts
packages/crypto-transaction-username-resignation/source/versions/1.ts
packages/crypto-transaction-validator-registration/source/versions/1.ts
packages/crypto-transaction-validator-resignation/source/versions/1.ts
packages/crypto-transaction-vote/source/versions/1.ts
packages/crypto-transaction/source/serializer.ts
packages/crypto-transaction/source/types/transaction.ts
packages/transactions/source/handlers/handler-registry.test.ts

Instead of allocating a way too large buffer when serializing transactions, we can precisely determine how big the buffer needs to be.

refactor(crypto): calculate tx buffer size

---

packages/crypto-transaction-username-registration/source/validation/schemas.test.ts
packages/crypto-transaction-username-registration/source/validation/schemas.ts

Allow only lowercase letters, numbers and underscores, underscores can be used only once in a row and not at the beginning or end of the string.

refactor(crypto-transaction-username-registration): stricter username regex

---

packages/crypto-transaction/source/deserializer.ts

Multisignaure check should use additional byte for musig index.

fix(crypto-transactions): use correct signature size checks in deserializer

---

packages/api-sync/source/service-provider.ts

Fix wrong initialization order and remove `postConstruct` in favour of service provider `boot`.

fix(api-sync): enable listeners during service provider boot

---

packages/api-http/source/controllers/peers.ts

We do not need total count estimation for the `peers` table. Other tables can grow quite large so we generally want to keep it for performance reasons.

refactor(api-http): disable total count estimation for peers table

---

packages/api-sync/source/listeners/abstract-listener.ts
packages/api-transaction-pool/source/controllers/transaction-pool.ts
packages/api-transaction-pool/source/routes/transaction-pool.ts
packages/configuration-generator/source/generators/genesis-block.ts
packages/contracts/source/contracts/crypto/block.ts
packages/contracts/source/contracts/crypto/transactions.ts
packages/contracts/source/contracts/transaction-pool/processor.ts
packages/crypto-block/source/factory.ts
packages/crypto-transaction/source/builders.ts
packages/crypto-transaction/source/factory.ts
packages/crypto-transaction/source/utils.ts
packages/transaction-pool/source/processor.test.ts
packages/transaction-pool/source/processor.ts

The transaction pool API now only accepts hex strings to remove the need to call `fromJson`. Furthermore, the id calculation can reuse the buffer directly instead of going through another transaction serialization.

perf: get rid of unnecessary transaction serializations

---

packages/consensus/source/consensus.ts
packages/consensus/source/processors/committed-block-processor.ts
packages/contracts/source/contracts/consensus/consensus.ts
packages/contracts/source/contracts/consensus/index.ts
packages/contracts/source/contracts/consensus/processor.ts

Await consensus handler to process block before checking if new block can be downloaded. Fixes the issue with multiple downloads for same block, which occurred because promise was resolved before height was increased. 
Consensus height and round are increased atomically, without intermediate awaits.

fix(p2p): await consensus handler on block download 

---

packages/contracts/source/contracts/transaction-pool/service.ts
packages/transaction-pool/source/service.ts

Dispatch `AddedToPool` when re-adding unconfirmed transactions on boot, so that the api-sync listener can pick them up.
Also remove unused `previouslyForgedTransactions` parameter and related code.

fix(transaction-pool): sync unconfirmed transactions on boot

---

packages/p2p/source/downloader/block-downloader.ts

Ban peer on communication and processing errors.

fix(p2p): ban peer on `getBlocks` error in BlockDownloader

---

packages/api-transaction-pool/source/routes/transaction-pool.ts
packages/crypto-transaction/source/builders.ts
packages/crypto-transaction/source/validation/formats.ts
packages/transaction-pool/source/defaults.ts

Change default value for `maxTransactionBytes` so it can handle a multipayment transaction with 256 recipients.

refactor: tweak default `maxTransactionBytes` and `vendorField` length

---

packages/api-transaction-pool/source/routes/transaction-pool.ts
packages/crypto-validation/source/keywords.ts

https://github.com/hapijs/hapi/blob/master/API.md#-routeoptionspayloadmaxbytes
The default is `1MB`, but we now set it based on the allowed number of transactions per request and maximum transaction bytes which at default values is equal to `~700kb`.

feat(api-transaction-pool): set `maxBytes` on route

---

packages/consensus/source/consensus.test.ts
packages/consensus/source/consensus.ts
packages/consensus/source/index.ts
packages/consensus/source/processors/precommit-processor.ts
packages/consensus/source/processors/prevote-processor.ts
packages/consensus/source/processors/proposal-processor.ts
packages/consensus/source/round-state-repository.ts
packages/consensus/source/storage.ts
packages/contracts/source/contracts/consensus/consensus.ts

Store state only at dispose to reduce writes to disk and improve sync performance.

perf(consensus): store state only at dispose

---

packages/cli/source/services/environment.test.ts

Fix unit test from polluting the working directory by resetting the environment variable.
```shell
$ git status -u
Untracked files:
packages/cli/something/mainsail/.env
```

test(cli): fix polluting working directory 

---

packages/consensus/source/consensus.test.ts
packages/consensus/source/consensus.ts
packages/contracts/source/contracts/validator.ts
packages/validator/source/index.ts
packages/validator/source/validator-repository.test.ts
packages/validator/source/validator-repository.ts
packages/validator/source/validator.test.ts
packages/validator/source/validator.ts
packages/validator/test/fixtures/validator-keys.ts

Don't generate wallet keys from validator.json. Consensus and wallet keys can be different.

refactor(validator): use `validators.json` to generate only consensus keys

---

packages/bootstrap/source/bootstrapper.ts
packages/contracts/source/contracts/state/index.ts
packages/contracts/source/contracts/state/state.ts
packages/contracts/source/contracts/state/store.ts
packages/contracts/source/identifiers.ts
packages/processor/source/block-processor.ts
packages/state/source/service-provider.ts
packages/state/source/service.ts
packages/state/source/state.test.ts
packages/state/source/state.ts
packages/state/source/store.test.ts
packages/state/source/store.ts

Extract `State` class which is responsible for holding blockchain state. In contract Store is used to store blockchain related logic, while state is used for the machine status and things, that don't need to be exported.

refactor(state): extract `State`

---

packages/core/bin/run

Discover libjemalloc.so without installed gcc. This adds support for docker builds without gcc.

feat(core): discover libjemalloc.so without installed gcc

---

packages/core/source/commands/config-forger-bip38.test.ts
packages/core/source/commands/config-forger-bip38.ts
packages/core/source/commands/config-forger-bip39.test.ts
packages/core/source/commands/config-forger-bip39.ts
packages/core/source/commands/config-forger.test.ts
packages/core/source/commands/config-forger.ts

Support `config:forger:bip39` similar to V3.
Used by e.g. the docker entrypoint: https://github.com/ArkEcosystem/mainsail/blob/develop/docker/production/entrypoint.sh#L20
Note that this also adds the BIP38 command (password encryption), but it's not doing anything yet.

feat(cli): support `config:forger:bip39` command

---

packages/api/bin/run

Discover libjemalloc.so without installed gcc. This adds support for docker builds without gcc.

feat(api): discover libjemalloc.so without installed gcc

---

docker/production/devnet/docker-compose-build.yml
docker/production/devnet/docker-compose.yml
docker/production/mainnet/docker-compose.yml
docker/testnet/README.md
docker/testnet/api/docker-compose-build.yml
docker/testnet/api/docker-compose.yml
docker/testnet/core/docker-compose-build.yml
docker/testnet/core/docker-compose.yml

- Use external docker network for both core and api containers.
- Update README.

chore: use external docker network

---

packages/contracts/source/contracts/evm/evm.ts
packages/contracts/source/contracts/evm/index.ts
packages/contracts/source/contracts/index.ts
packages/crypto-transaction-evm-call/package.json
packages/crypto-transaction-evm-call/source/handlers/evm-call.ts
packages/evm/package.json
pnpm-lock.yaml

The `@mainsail/crypto-transaction-evm-call` package should not depend on `@mainsail/evm`  otherwise we get a cyclic dependency:
```
There are cyclic workspace dependencies: mainsail/packages/crypto-transaction-evm-call, mainsail/packages/evm, mainsail/packages/test-framework
```
To break it up add evm interface definitions to `@mainsail/contracts` and remove the `@mainsail/evm` dependency from `@mainsail/crypto-transaction-evm-call`.

refactor(crypto-transaction-evm-call): add interface types to break up cyclic dependency on evm

---

packages/api-common/source/rcp/processor.ts
packages/api-common/source/rcp/utils.ts
packages/api-evm/package.json
packages/api-evm/source/actions/call.ts
packages/contracts/source/exceptions/index.ts
packages/contracts/source/exceptions/rpc.ts
packages/crypto-validation/source/schemas.ts
packages/evm/package.json
packages/evm/source/instance.test.ts
packages/evm/test/fixtures/wallets.ts
pnpm-lock.yaml

Support `evm_call` method. Use correct request schema.
Add support for custom JSON-RPC errors. 
**balanceOf** can be checked using following data:
```
{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0xBd6F65c58A46427AF4B257cBE231D0eD69eD5508", "to": "0xD3D80a3Df661414a76aAd7738a136A8d7aAa1666","data":"0x70a08231000000000000000000000000bd6f65c58a46427af4b257cbe231d0ed69ed5508"}, "latest"],"id":1}
```
or request:
```
curl --location 'http:/127.0.0.1:4008/api/' \
--header 'Content-Type: application/json' \
--data '{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0xBd6F65c58A46427AF4B257cBE231D0eD69eD5508", "to": "0xD3D80a3Df661414a76aAd7738a136A8d7aAa1666","data":"0x70a08231000000000000000000000000bd6f65c58a46427af4b257cbe231d0ed69ed5508"}, "latest"],"id":1}'
```

feat(api-evm): support `evm_call` method

---

packages/api/source/commands/env-paths-clear.ts
packages/api/source/commands/env-paths.ts
packages/cli/source/application.ts
packages/cli/source/contracts.ts
packages/cli/source/services/environment.ts
packages/core/source/commands/env-paths-clear.ts
packages/core/source/commands/env-paths.ts

Clear folders on the predefined paths. Options:
- state-export
- plugins
- data
- config
- cache
- log
- temp
- all

feat: add `env:paths:clear` commands

---

packages/crypto-transaction-username-registration/source/handlers/username-registration.ts

Allow only 1 TX by sender in pool.
Fix error message.

feat(crypto-transaction-username-registration): limit one transaction by sender in pool

---

packages/contracts/source/contracts/p2p/endpoints.ts
packages/contracts/source/contracts/transaction-pool/processor.ts
packages/test-framework/source/mocks/transaction-pool-processor.ts
packages/transaction-pool/source/processor.test.ts
packages/transaction-pool/source/processor.ts

Previously it would return a transaction id or an index, but this is no longer the case and now it always returns an index. Update the response to reflect it.

refactor(transaction-pool): return tx indexes as integers

---

packages/api-http/integration/routes/delegates.test.ts
packages/api-http/integration/routes/wallets.test.ts
packages/api-http/source/controllers/delegates.ts
packages/api-http/source/controllers/wallets.ts

Use `responseWithResource` so it correctly returns 404 if a wallet does not exist. Also makes the returned payload consistent with the other controllers.
This is a breaking change as it now wraps the returned resource in `{  "data": {  ... } }`.
See before and after comparison.
<details>
<summary>Before</summary>
**Existing wallet**
```
/api/wallets/DA6dECuctJRW9W2AVZhWNrzftD4eSXmoon
{
"address": "DA6dECuctJRW9W2AVZhWNrzftD4eSXmoon",
"publicKey": "03c521450f8fb765d7ee2fd3cabfd0ab0138ecc5ae4d69d47ed910088183c52451",
"balance": "140488000000",
"nonce": "7",
"attributes": {
"vote": "03c521450f8fb765d7ee2fd3cabfd0ab0138ecc5ae4d69d47ed910088183c52451",
"nonce": "7",
"balance": "140488000000",
"username": "arkmoon",
"publicKey": "03c521450f8fb765d7ee2fd3cabfd0ab0138ecc5ae4d69d47ed910088183c52451 …
```

fix(api-http): wallet resource response

---

packages/api/package.json
packages/api/source/commands/api-start.test.ts
packages/api/source/commands/api-start.ts
packages/core/package.json
packages/core/source/commands/core-start.test.ts
packages/core/source/commands/core-start.ts
packages/test-framework/source/cli/console.ts

fix: use .js extension in `start` commands

---

packages/api-database/source/models/configuration.ts
packages/api-http/integration/routes/node.test.ts
packages/api-http/source/controllers/node.ts
packages/api-sync/source/service.ts

Sync active milestones to the `configuration` table on milestone change so that the API can easily use them.
NOTE: Since this adds a new table column it requires a postgres reset.

fix(api): sync active milestones on change

---

packages/api-common/source/server.ts
packages/api-http/source/controllers/blocks.ts
packages/api-http/source/controllers/controller.ts
packages/api-http/source/controllers/transactions.ts
packages/api-http/source/controllers/votes.ts
packages/api-http/source/controllers/wallets.ts
packages/api-http/source/resources/block.ts
packages/api-http/source/resources/transaction.ts

Fix the `TransactionResource` not returning `timestamp`, `signatures` and `confirmations`.  
Regarding the sender address , a client can just calculate it from `senderPublicKey` with an appropriate `AddressFactory` so we don't really need to have it on the API response.

fix(api-http): add missing fields to transaction resource

---

packages/transaction-pool/source/processor.ts

Ensure transaction deserialization is awaited so any thrown error is wrapped correctly.
```
curl -X POST "http://localhost:4007/api/transaction-pool" -H "Content-Type: application/json" -d '{"transactions": ["3452344"]}'
```
Before:
```json
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "An internal server error occurred"
}
```
After:
```json
{
"data": {
"accept": [],
"broadcast": [],
"excess": [],
"invalid": [
0
]
},
"errors": {
"0": {
"message": "Invalid transaction data: Failed to deserialize transaction, encountered invalid bytes: Attempt to access memory outside buffer bounds",
"type": "ERR_BAD_DATA"
}
}
}
```

fix(transaction-pool): invalid tx error reporting

---

packages/api-database/source/service-provider.ts
packages/api/source/cli.ts
packages/api/source/commands/api-run.ts
packages/api/source/commands/config-publish.ts
packages/cli/source/services/source-providers/npm.test.ts
packages/configuration-generator/source/generators/app.ts
packages/core/source/cli.ts
packages/core/source/commands/config-publish.ts
packages/core/source/commands/core-run.ts
packages/crypto-worker/source/service-provider.ts
packages/kernel/source/bootstrap/load-service-providers.test.ts
packages/kernel/source/bootstrap/load-service-providers.ts
packages/kernel/source/bootstrap/register-base-bindings.ts
packages/p2p/source/hapi-nes/plugin.ts
packages/test-framework/source/factories/factories/block.ts
packages/test-framework/source/factories/factories/identity.ts
packages/test-framework/source/factories/factories/transaction.ts
packages/test-framework/source/factories/helpers.ts

Remove usage of __dirname, because it is part of CJS.

refactor: remove `__dirname` usage

---

packages/api-development/source/controllers/blocks.ts
packages/bootstrap/source/bootstrapper.ts
packages/contracts/source/contracts/database.ts
packages/database/source/database-service.test.ts
packages/database/source/database-service.ts
packages/p2p/source/peer-verifier.ts

- Return commit instead blocks.
- `getLastCommit` throws if database is empty
- add `isEmpty` method

refactor(database): return commits instead blocks

---

packages/transaction-pool/package.json
packages/transaction-pool/source/storage.test.ts
packages/transaction-pool/source/storage.ts
pnpm-lock.yaml

Support in-memory database using `:memory:` as filepath.

feat(transaction-pool): support `in-memory` database

---

packages/api-http/integration/routes/transactions.test.ts
packages/api-http/source/controllers/controller.ts
packages/api-http/source/controllers/node.ts
packages/api-http/source/controllers/transactions.ts
packages/api-http/source/routes/transactions.ts
packages/api-http/test/fixtures/transactions_fees.json

Works same as https://api.ark.io/api/transactions/fees
```shell
curl localhost:4003/api/transactions/fees | jq
{
"data": {
"1": {
"transfer": "10000000",
"validatorRegistration": "2500000000",
"vote": "100000000",
"multiSignature": "500000000",
"multiPayment": "10000000",
"validatorResignation": "2500000000",
"usernameRegistration": "2500000000",
"usernameResignation": "2500000000"
}
}
}
```

fix(api-http): implement missing `/transaction/fees` route

---

packages/api-http/test/fixtures/node_configuration.json
packages/api-sync/source/listeners/api-nodes.ts
packages/api-sync/source/listeners/mempool.ts
packages/api-sync/source/listeners/peers.ts
packages/api-sync/source/listeners/plugins.ts
packages/configuration-generator/source/application-factory.ts
packages/configuration-generator/source/configuration-generator.test.ts
packages/configuration-generator/source/generators/milestones.test.ts
packages/configuration-generator/source/generators/milestones.ts
packages/consensus/source/scheduler.test.ts
packages/consensus/source/scheduler.ts
packages/contracts/source/contracts/crypto/networks.ts
packages/core/bin/config/testnet/core/crypto.json
packages/crypto-config/source/configuration.test.ts
packages/kernel/source/utils/timestamp-calculator.ts
tests/e2e/consensus/nodes/node0/core/crypto.json
tests/e2e/consensus/nodes/node1/core/crypto.json
tests/e2e/consensus/nodes/node2/core/crypto.json
tests/functional/consensus/config/crypto.json
tests/functional/transaction-pool-api/paths/config/crypto.json

Block prepare time is minimal time ensured for the proposer to prepare a block. If time between commit and remaining blockTime is less than blockPrepareTime, blockPrepareTime will be used delaying the round start, otherwise new round begins when blockTime times out. 
Milestone timeout values are rearranged under timeouts property.

feat: add `blockPrepareTime` to milestones

---

packages/api-sync/source/service.ts

Resolve errors such as `sync encountered exception: bind message has 18464 parameter formats but 0 parameters` when processing blocks containing >1000 transactions.

fix(api-sync): process transactions in chunks to support very large blocks

---

packages/validator/package.json
packages/validator/source/defaults.ts
packages/validator/source/index.ts
packages/validator/source/validator.ts
packages/validator/test/helpers/prepare-sandbox.ts
pnpm-lock.yaml
tests/functional/consensus/config/crypto.json
tests/functional/transaction-pool-api/paths/config/crypto.json

Limit transaction collation to 75% of the time. Remaining time is used for block creations and signing.

feat(validator): time limit transaction collation

---

packages/contracts/source/contracts/transaction-pool/mempool.ts
packages/contracts/source/contracts/transaction-pool/sender-mempool.ts
packages/contracts/source/contracts/transaction-pool/sender-state.ts
packages/contracts/source/contracts/transaction-pool/service.ts
packages/transaction-pool-service/source/mempool.test.ts
packages/transaction-pool-service/source/mempool.ts
packages/transaction-pool-service/source/sender-mempool.test.ts
packages/transaction-pool-service/source/sender-mempool.ts
packages/transaction-pool-service/source/sender-state.ts
packages/transaction-pool-service/source/service.ts
packages/transaction-pool-worker/source/handlers/commit.ts
packages/transaction-pool-worker/source/handlers/get-transactions.ts
tests/functional/transaction-pool-api/source/pool-worker.ts

Re add transactions:
- forged transaction is not same as first transaction
- transaction is removed because: old, expired or low priority
- discard removeTransaction method, service is self sustainable

feat(transaction-pool-service): re-add transactions on invalid states
